#+TITLE: A Crisis is a Terrible Thing To Waste
#+OPTIONS: num:nil; ^:nil; ':t

* Publication Details
+ Published by: Brookings Institution
+ Publication Link: https://www.brookings.edu/wp-content/uploads/2019/01/fp_20190118_hass_a_crisis_is_a_terrible_thing_to_waste.pdf
+ Author: Ryan Hass

* Introduction
+ When Nixon and Zhou Enlai signed the Shanghai Communique, there was no reason to believe that the US and China would have a successful rapprochement
  + Korean War was still a fresh memory
  + US had an ongoing struggle against a Communist state in the form of the Vietnam War
    + /But note: that communist state was actually opposed to China!/
    + /Vietnam was allied with the Soviet Union, whom China opposed/
  + China was locked in the throes of the Cultural Revolution
  + There was no constituency on either side pushing for closer relations
+ Today the US/China bilateral relationship is the most significant in the world
+ US and China are the two most consequential actors on the world stage
+ China has transformed itself from a weak, divided, poor country into the United States' foremost strategic competitor
+ The US/China relationship has reached a "tipping point"
  + The basic assumptions and expectations from the last 40 years no longer hold
  + Do not have a new set of expectations and assumptions to replace them
+ The current turbulence reflects both risks and opportunities

* How did we get here?
+ There are three contrasts between the initial stages of the US-China relationship and today
  + Information
    + In the 1970s, China was still very much a closed society
      + Scholars in the West confined themselves to historical and cultural assessments of China
      + Assessments of contemporary events were distant and "birds-eye"
      + The act of studying China in the US was freighted with the risk of appearing ideologically sympathetic to Communism
    + Today China and the US have much more information about each others' internal state
      + Information about events in China, even in remote areas, elicits real time reactions from the United States
      + /I dispute this point. I don't think information about remote areas of China is as abundant as Hass thinks it is/
      + /I would also question the quality of the information -- China is known to cook its books and its pervasive censorship of media and internet provides the state plenty of opportunities to make things seem different than how they're actually perceived at "ground level"/
      + China specific expertise is no longer required for people to feel comfortable giving opinions of China's impact on their field
        + Technologists look at China's technological advancements to argue that the US should be experiencing a new "Sputnik moment"
          + /Leaving aside the fact that the "Sputnik moment" had as much to do with internal domestic politics as it did with actual launch of Sputnik/
          + /The real Sputnik moment wasn't the actual launch of Sputnik but rather was the way JFK used it to portray the Eisenhower administration as being "soft" on national security/
        + Grand strategists talk about China as the next challenger for US superiority
  + The strategic nature of the relationship
    + Until the 1990s, China was seen as a strategic asset to the US, not a competitor
    + China was seen as a counterbalance to the Soviet Union
    + After the end of the Cold War, China's rapidly expanding economy and military made it seem more a competitor than an ally
  + Generational shift in policymakers
    + Earlier generation of policymakers -- people like George H.W. Bush, Brent Scowcroft, Zbigniew Brzezinski, etc -- had specialization in China, and enjoyed prestige within their own parties
    + While some viewed the relationship as a means to an end -- balancing the Soviet Union, none was specifically hostile towards China
    + Felt that a strong US/China relationship was in the United States' strategic best interest
    + Today there are no heirs to the old generation who advanced US/China relations
      + Current senior officials have relatively little experience with China
      + Less comfortable focusing on the broader strategic picture
      + Less inclination to craft long-term strategy
      + /How much of this, though, is cause, and how much is effect/
      + /Very similar points can be made across the entirety of the US government/
      + /It's hard to make long-term plans in any area when you don't know what funding levels are going to be like six months from now/
    + As a result, the US doesn't really know what role China should play in US grand strategy
      + /Insofar as the US even has a grand strategy at this point/
+ The path to the current relationship hasn't been a smooth upward climb
  + In the early '80s, the US had an optimistic view of China
  + Many saw Deng Xiaoping as a reformer
  + There was a sense that China would go down the path of Taiwan and South Korea, both of which had shed their dictatorships in favor of democracy
  + These hopes were shattered in 1989, when China used force to suppress student protests in Beijing
  + Relations sank further when China attempted to influence Taiwanese elections in 1995-96, which led the Clinton administration to send two carrier strike groups into the Taiwan Strait
  + /This is why China has been so single-minded in its focus on acquiring and developing anti-access/area-denial technologies (A2AD) -- Clinton's intervention was humiliating for the Chinese leadership and underscored China's strategic vulnerability to US sea power/
  + Following the Taiwan crisis, the Clinton administration pursued a strategy of "comprehensive engagement" to ensure that there were lines of communication which would help prevent future misunderstandings and conflict
  + These efforts culminated in Clinton being the first American president to visit China in 9 years in 1998, followed by China's accession to the WTO
  + Clinton sold the deal as a way that the US could use economics to force political liberalization in China
    + However, the internal rationales that the administration used did *not* mention political liberalization as a rationale
  + After China became a WTO member in 2001, the United States' focus became one of trying to integrate China into a "rules-based" international order
  + This has had some significant successes
    + China has cooperated much more than in the past on efforts to contain Iranian and North Korean nuclear programs
    + Adhered to international agreements on weapons of mass destruction
    + Cooperated with the US in addressing the global financial crisis of 2007
    + Become a major contributor to the World Bank and International Monetary Fund
    + Implemented steps to stop trafficking in endangered species and improved environmental protections
+ Now, however, China is seen as much as a competitor as a partner
  + China's rise has dovetailed with a period of national self-doubt in the United States
    + Defeats in Iraq and Afghanistan
    + Growing economic inequality
    + China is blamed (rightly or wrongly) for taking advantage of American markets at the expense of the American worker
  + China has become more aggressive, both at home and abroad
    + China has replaced a foreign policy of patience and modesty ("hide your strength and bide your time") for a bolder more aggressive foreign policy
    + More coercive actions with regards to
      + South China Sea
        + Building island bases
        + Pushing around (literally) Filipino fishing vessels
      + Taiwan -- Chinese rhetoric has become more strident with regards to suggesting that China and Taiwan will be reunified, by force if necessary
      + India -- Chinese and Indian soldiers getting into shoving matches along the de facto border in Arunachal Pradesh (specifically, the tri-border area around Doklam)
      + US -- Xi Jinping has placed less importance on maintaining a stable relationship with the United States than his predecessors
  + Elites in the US have lost confidence in the ability of the United States to influence the Chinese leadership
    + Deeper engagement has not resulted in political liberalization
    + There is a growing consensus that the US relationship with China has benefited China at the expense of the United States
+ Two caveats to this growing criticism of the United States' China policy
  + Divergence between expert opinion and public opinion -- public opinion is largely split on whether China is a partner or a rival -- members of US public don't have as negative an opinion of China as US policymakers and analysts
  + There continue to be significant dissenting voices in the US policy-making establishment against a more adversarial relationship with China
+ Nevertheless, there appears to be widespread agreement that US-China relations are at their most strained since Nixon's 1972 trip

* Why Might This Time Be Different
+ While the relationship over the past 40 years has had cyclical swings, the overall trend has been towards broadening and deepening of the relationship
+ However, the US/China relationship may have entered a structural change towards a more adversarial relationship
+ Implicit compact governing relations between the two countries has frayed
  + US implicitly had agreed to refrain from impeding China's development nor make statements about how China should govern itself
  + China implicitly had agreed to refrain from challenging the US for global leadership and displacing the US from Asia
+ Today, both sides hold that the other has violated the compact
  + Washington experts see China's building of alternate institutions and naval buildup in the South China Sea as clear signs of a Chinese attempt to displace American hegemony in Asia
  + A large body of Chinese experts see the US position as an impediment to China achieving its rightful destiny
    + US tariffs are intended to slow or prevent the Chinese economy from overtaking the US economy
    + US involvement in Taiwan and Hong Kong is seen as encouraging political dissent within China
+ The Trump administration has weaponized China as an issue in American domestic political discourse
  + 2017 National Security Strategy mentioned China as a "strategic competitor" and "revisionist power"
  + Contrast with the 2015 NSS, which mentioned a "stable, peaceful, and prosperous China"
  + This rhetorical shift matches the mood of Trump's political base
    + Many jobs have been lost to China
    + Losses concentrated in areas that voted for Trump
    + The rise of China has provided politicians an easy scapegoat upon which to shift blame for localized economic stagnation
    + As a result, many Americans feel that China is the chief threat to American prosperity
+ The Chinese, however, are not entirely blameless
  + Willfully disregarding international market norms
  + Industrial policy
  + Market access restrictions
  + Technology transfer requirements
+ Both sides assign lower value to interdependence than they used to
  + Past American administrations viewed interdependence as a stabilizing force
  + Trump administration sees interdependence as working to China's advantage at the expense of the United States
  + Xi Jinping as accepted greater friction with the United States as an acceptable cost of having a more assertive foreign policy and statist economic policy
+ US/China competition has assumed an ideological dimension
  + Previously, absence of US/China ideological competition stood in contrast to US/Soviet Union ideological competition
  + While the ideological competition is less intense than it was between the US and the Soviet Union, there is an acknowledged difference in ideologies
  + US policy communities have seized on statements by Xi Jinping about a "China model"
    + State-led economics
    + Authoritarian governance
  + While there is scant evidence that China seeks to export its model, measures in the PRC may be providing inspiration to other authoritarian regimes
  + The adoption of measures similar to the Chinese government normalizes China's governance model and allows China to further tighten control over its society in the name of stability

* What is at stake
+ The decline in US-China relations presents both risks and opportunities
+ Risk:
  + Prolonged period of confrontation, possibly leading to conflict
  + Even if armed conflict does not occur, there will be less scope for cooperation on matters that affect both countries
  + Might lead to further efforts to decouple economies, leading to slower economic growth and higher inflation
    + /On the other hand, maybe slower economic growth and higher inflation is worth it if the gains from said economic growth are more evenly distributed/
    + /Arguably, somewhat higher inflation is *good* for Americans, as it would ease the pressure on borrowers/
  + The catastrophic risk is that ongoing tensions between China and the US escalate like tensions between Germany and Great Britain in the run-up to World War 1

* What can be done
+ Leaders in Washington and Beijing should use this time to examine their assumptions about the type of relationship they want to have with the other power
+ Shared strategic imperative that brought both countries together no longer exists
+ No longer a belief in the mutual benefits of deepening ties
+ Four questions for the US policy community:
  1. What is the objective of US policy towards China
     + We must abandon the thought that we can impose our will on China
     + Unrealistic to assume that China will become more like the US
     + Unrealistic to assume that the US will get a vote or veto in Chinese policy
     + By the same token, Chinese attempts at manipulating US internal policy debates should also be seen as unacceptable
     + So what is reasonable?
       + We should expect China to take more responsibility for dealing with transnational threats -- doing so is in China's best interests as well as ours
       + Reasonable to expect China's economy to become more market oriented -- greater economic growth is something that the Chinese government desires as it pursues modernization
         + /Is this true, though?/
         + /It seems to me that Xi Jinping, like Donald Trump, is willing to forego economic growth in order to pursue other geopolitical objectives/
     + It will not serve the US to paint the Chinese as an adversary
     + Instead the US should out-compete China
       + /If we're in competition with them, they're our adversary/
     + The US should work with China to share the load of handling global challenges
       + /The problem is that China has displayed no proclivity towards "handling global challenges"/
       + /China is content to let the US handle global trouble-spots/
       + /Moreover, the current Chinese foreign-policy worldview is a strictly Westphalian model -- states are considered to be completely sovereign, and no state has the right to interfere in the internal affairs of another state, no matter how horrendous/
       + /I see very little evidence to suggest that a world under Chinese hegemony would be more respectful of human rights or would be better able to deal with transnational threats/
  2. Can the United States live with a rising China?
     + There is a growing chorus of policy-makers who suggest that in order to preserve US prosperity, the US must restructure itself to stymie China
     + If such views gain sustained expression in American policy, it is likely that Beijing will abandon whatever conciliatory posture it currently has and will adopt a more hostile approach to the US and its partners
     + The US needs to determine what it will gain and lose by attempting to torpedo Chinese growth
     + Will also need to determine whether it can achieve this objective at acceptable cost
     + A Chinese downturn will hurt US growth and prosperity as well
     + The US needs to ask itself whether it benefits more from a strong and capable China or an internally weak and externally insecure China
     + In the recent past, when China was more insecure, it employed a more disruptive foreign policy
       + Stoked nationalism over Taiwan
       + Cultivated closer ties with North Korea
     + The US needs to determine whether it can gain support for a more China-hostile strategy from its allies
       + During the Cold War, Western Europe's trade ties with the Soviet bloc were minimal
       + In contrast, every country on the Pacific rim counts China as its #1 or #2 trading partner
       + It's very well possible that a more overtly hostile China strategy would dissuade our allies, leading to the US becoming less able to influence Chinese policy
  3. Where should China have a greater say on matters of global governance?
     + Every rising global power has sought to adapt the international system to accommodate its new status
     + The US, so far, has been more inclined to obstruct increasing Chinese influence in international institutions
     + The US would gain more support from its allies if it supported China taking a role in international instutions commensurate with its power
     + The US could then insist that China use its power in a way that supports existing institutions, rather than undermining them
       + /On the other hand, China could then use its power to render said institutions ineffective/
     + If the US continues to reflexively obstruct China from gaining a greater voice on the world state, all it will do in the long term is isolate itself
       + /I think that depends on whether, in the long term, other countries find China's growth more appealing than the US/
       + /I don't think US isolation is as inevitable as Haas says it is, especially once other countries find out about the downsides of Chinese investment and expansion/
  4. What are both sides' visions for regional order in Asia?
     + The US and China should understand each others' expectations and ambitions in Asia
     + We need a sustained, authoritative, bilateral dialogue
     + The Asia-Pacific is where US and Chinese interests intersect most directly and where relative power is shifting most rapidly
     + 70 years of uncontested US supremacy in the Pacific is giving way to a more even distribution of power
     + Both sides need to shrink the gap in expectations in order to prevent conflict
     + The US needs to make its objectives clear to China
       + Committment to open markets
       + Ensure that all states are respected, regardless of power
       + Determination to apply global norms evenly across the global commons
       + /Let's be clear: these aren't US objectives. These are the objectives of a very particular Obama/Clinton policy-wonk class within the US/
       + /There are lots of others within the US who would be happy to see a more confrontational stance towards China/
       + /Equally, there are others (though, a smaller group) who would like to see the US "give up" on maintaining control over the Pacific/
     + The US should make it clear that China's growing power does not exempt it from the rules that bind other actors in the region
       + /Forgetting, conveniently, that those rules were created by the US itself/
       + /Forgetting conveniently, that the US chooses to ignore its own rules all the time/
     + The US should resolve to oppose the establishment of spheres of influence (regions where a power enjoys special and exclusive privileges in any part of Asia)
       + /Forgetting, conveniently, that the US gets a giant naval base at Yokosuka, and several giant army bases in Korea/
       + /Forgetting, conveniently that the US owns the island of Diego Garcia/
  5. What role should other powers in the region play?
     + /You said there would be four questions!/
     + The US should assign a high priority to fortifying its partnerships and drawing support for its vision for the future of the region
     + Strengthen regional support for a common set of rules and norms
     + This will not constrain China's growth, so long as China operates within the existing rules-based regional architecture
       + /So it will constrain China's growth/
       + /He forgets that the entire rules-based regional architecture was designed by the US in the '90s to constrain China/
     + If China steps beyond the rules, committing to a rules-based order will allow the US to coordinate more effectively with its allies in opposing China
     + China will object to the maintenance of these alliances
     + The US should be clear with Beijing about the full range of threats they are organized to address
     + Doing so will enable Beijing to see the non-negotiable nature of the alliances and will push Beijing towards regional challenges where it can have influence
       + /tl;dr: Go bother India/

* Conclusion
+ The US-China relationship has evolved considerably over the past 40 years
+ The sharp deterioration in bilateral relations in the past few months likely represents a structural shift in the relationship
+ The sooner that leaders on both sides recognize that this shift isn't just due to the vagaries of an unconventional US President, the sooner we'll be able to reset the relationship
+ There is no constituency within the US that wishes a return to the pre-Trump US-China relationship
+ The task is to re-imagine the US-China relationship in a manner that allows for peaceful coexistence while attracting durable bipartisan support
+ America needs to understand its strengths vis-à-vis China
  + Global alliance network
  + Unmatched power projection
  + Deep capital markets
  + Culture of innovation
+ America can outcompete China over the long-run
+ A competitive, but stable relationship with China is more conducive to American security and prosperity than outright hostility
