#+TITLE: The Challenger Launch Decision
#+OPTIONS: num:nil; ^:nil; ':t

+ Author: Diane Vaughan
+ Publisher: University of Chicago Press
+ Publication Date: 2016

* Preface:
+ The Challenger disaster is one of those rare events that bound together diverse people in a moment of shared anguish
+ Disaster is remembered as a technical failure
  + Fault lay with rubber-like O-rings
  + O-rings were designed to seal up tiny gaps in the solid rocket boosters
  + Cold weather impaired the resiliency of the O-rings
  + When O-rings failed, hot exhaust gases from the solid rocket booster impinged on the large external fuel tank
  + Fuel tank failed causing loss of crew and orbiter
+ However, the NASA organization was also implicated
  + O-ring problem had a long history at NASA
  + Documents detailing problems with the O-rings date back to 1977, 4 years before the first shuttle flight
  + Presidential commission investigating the disaster found that there was a midnight teleconference the night before the launch where Morton Thiokol (the manufacturers of the SRBs) warned against the launch
+ So given that Thiokol warned against the launch and that the O-ring issue was well known, why did NASA proceed with the launch?
+ House committee investigating the incident and journalists crafted a narrative explanation involving production pressure and managerial wrongdoing
  + NASA had been undergoing enormous stress
  + Managers were under pressure to stick to a launch schedule, in order to secure funding for NASA
  + Managers flouted internal NASA rules which called for information to be passed up the chain, ensuring that top administrators did not have the information they needed
+ This model explains the actions of top administrators, but does not explain the actions of low and mid-level managers
  + Why did they choose to proceed with the launch, despite having all the information?
  + This question went unasked and unanswered as people came to accept the explanation in the press that production pressures caused NASA officials to withhold information that would have stopped the launch
+ This book contradicts that conventional explanation
  + Presents evidence that contradicts the conventional explanation
  + Seeks to answer the question: "Why did NASA, in the years prior to the launch, choose to proceed with a design known to be flawed?"
+ Books seeks to circumvent hindsight bias - tries to present technical choices as they appeared to participants at the time, not as they were seen later on
+ Portrays a gradual descent into poor judgment
+ Shows that signals of potential danger were normalized prior to 1986
+ This normalization proceeded according to social forces and environmental contingencies which impinged upon the organizational structures and culture of NASA
+ This affected the worldview of NASA engineers and managers as they were making decisions and how the processed information regarding the booster joints
+ While production pressure did have a role in the tragedy, it was not the role that most press accounts assign to it
+ This book shows how mistake, mishap and disaster are systematically produced by social forces
  + Shows how people doing their jobs properly can still contribute to a disaster
  + Show how scientific paradigms are constructed and how they persist even in the face of growing evidence to the contrary
  + Shows how incremental decisions in organizations can contribute to dramatic disasters
+ In addition to that, the book demonstrates the macro/micro connection - showing how macroscopic forces in an organization contribute to individual day-to-day decisions that people make
+ The goal of this book is to show that harmful accidents can occur in organizations specifically built to prevent them from occurring, even when everyone in the organization is honest, conscientious, and ethical

* Chapter 1: The Eve of the Launch
+ /Challenger/ was originally scheduled for launch on January 22, 1986
+ Crew
  + Richard Scobee - Commander
  + Michael Smith - Pilot
  + Ellison Onizuka - Mission Specialist
  + Judith Resnik - Mission Specialist
  + Ronald McNair - Mission Specialist
  + Christa McAuliffe - Payload Specialist
  + Gregory Jarvis - Payload Specialist
+ Officially known as STS-51L
+ Christa McAuliffe was a teacher, and was going to teach lessons from orbit, hence this mission was nicknamed as the "Teacher In Space" mission
+ Although the launch was originally scheduled for January 22, it was "slipped" to January 26 to accommodate the launch of Columbia (STS-61C)
  + STS-61C set a record for launch delays by having 7 launch delays over a 25-day period
  + Originally scheduled for December, didn't actually launch until January 12
+ Challenger launch was coordinated by a 4-tier management chain at NASA
  + Level 1: Jesse Moore -- Associate Administrator For Space Flight (NASA HQ, Washington) 
  + Level 2: Arnold Aldrich -- Program Manager - Johnson Space Center (Houston) 
  + Level 3:
    + William Lucas - Director - Marshall Space Flight Center (Huntsville)
    + Stanley Reinartz - Manager - Shuttle Projects Office, Marshall
    + Lawrence Mulloy - Manager - Solid Rocket Booster Project, Marshall
  + Level 4: Alan McDonald - Director, Solid Rocket Motor Project, Morton Thiokol (Utah)
+ On January 26, countdown activities were terminated because the forecast showed unacceptable weather conditions
+ On January 27, the countdown was terminated because of micro-switch indicators that showed that the exterior hatch locking mechanism had not closed properly
+ NASA personnel first became concerned about cold temperatures at around 1:00pm on January 27
  + Forecast was unusually clear and cold for Florida, with temperatures dropping into the low 20s
  + Marshall's Larry Wear (SRM manager) asked Morton-Thiokol Wasatch (Utah) to review possible effects of cold on the performance of the SRM
  + This request was handled by Robert Ebeling, Ignition Systems Manager
  + Ebeling convened a meeting, and Thiokol engineers expressed concern that the O-rings would not be able to seal after being exposed to such cold temperatures
+ A 3-way conference call was scheduled between Kennedy Space Center (KSC), Marshall and Morton Thiokol for 5:45pm EST -- during this call, Morton Thiokol expressed the opinion that the launch should be delayed until noon or later
+ Another conference call was scheduled for 8:15pm EST, to allow Morton Thiokol to fax over engineering data and to allow more people to join the conference
  + In this conference call, Thiokol engineers presented their opinion that O-ring performance would be worse than the coldest launch to date (1985 mission, where the O-ring temperature was 53F)
  + On that mission, hot exhaust gases had blown past the primary O-ring, however the secondary O-ring had done its job and sealed the booster joint
  + Thiokol VP of Engineering Robert Lund's opinion was that at O-ring temperatures colder than 53F, the ability of the O-rings to seal would be compromised
  + NASA asked Thiokol management for a recommendation -- VP Joe Kilminster agreed with the engineers and said that he could not recommend launching at any temperature below 53F
  + NASA immediately began challenging this assertion
  + Mulloy argued that there had never been Launch Commit Criteria on O-ring temperatures, so Thiokol was, in essence, creating new Launch Commit Criteria on the eve of a launch
  + Reinartz asked Deputy Director of Science and Engineering George Hardy for his opinion -- Hardy concurred with Reinartz and Mulloy and said that he was "appalled" at Thiokol's recommendation
  + Mulloy asked, "My god Thiokol, when do you want me to launch? April?"
  + Reinartz asked Kilminster for his comments; Kilminster requested a 5 minute offline caucus
    + 5 minute caucus stretched to 30 minutes
    + During this caucus, Thiokol Senior Vice President Jerry Mason said, "We have to make a management decision," excluding engineers from the decision-making
    + Thiokol engineers Arnie Thompson and Roger Boisjoly presented the case against launching once again to the Thiokol management team
    + 4 Thiokol Vice-Presidents voted -- Robert Lund initially voted against the recommendation to launch, but was asked by Mason to "take off your engineering hat and put on your management hat"
    + Lund then voted for the recommendation to launch
  + After the offline caucus was over, Thiokol rejoined the conference call with KSC and Marshall
    + Kilminster said that Thiokol had reconsidered, and read a revised engineering analysis supporting launching
    + Mulloy asked Kilminster to fax the engineering analysis to Marshall and KSC
  + The second teleconference ended at around 11:15pm EST
+ After the second teleconference, Mulloy and Reinartz phoned Aldrich about ice buildup on the launchpad and the status of the recovery ships for the SRBs
+ Did not inform Aldrich about the teleconference with Thiokol and KSC meeting broke up around midnight EST
+ At 1:30am EST the Ice/Frost inspection team assessed the ice buildup on the launchpad and alerted Rockwell to study the effects of ice buildup on the orbiter
+ At 5:00am the next morning, Mulloy and Reinartz told William Lucas and James Kingsbury, head of the Science and Engineering Department, about the teleconference with Thiokol
+ At 7:00am the ice inspection made a second inspection -- launch time was slipped to allow for a third round of inspections
+ At 8:30am the Challenger crew were strapped in
+ At 9:00am the Mission Management Team met with NASA and contractor representatives to assess launch readiness and the ice situation
  + Rockwell representatives expressed concern about the possibility of ice ricochets hitting the orbiter
  + Mission Management Team noted the concerns and voted to launch
+ Terminal countdown began at 11:25am
+ Orbiter was launched at 11:38am on January 28 1986
+ A fireball erupted 73 seconds later and the orbiter disappeared into a huge cloud of smoke
+ The SRBs careened out of control and were destroyed by an Air Force range safety officer at T+110 seconds
+ All seven crew members perished

** The Search For An Explanation: Creating History
+ In February, President Reagan established a commission (Rogers Commission) to investigate the /Challenger/ disaster
+ NASA had already started its own investigation into the matter
+ Initially, the Rogers Commission saw its role as one of collaborative oversight
+ Commission began hearings on Thursday February 6, 1986
  + Initially, the commission reviewed evidence from NASA about the current state of the NASA investigation
  + Initial NASA testimony to the commission downplayed the role of the O-rings, by noting that while erosion of the primary O-rings had been observed, erosion of the secondary O-rings had never been been observed
  + However on Sunday, February 9, the New York Times published leaked documents that called the O-rings into question, stating that seal erosion had occurred 12 times, and that on one occasion the secondary O-ring /had/ been eroded
+ After the NY Times story, the Rogers Commission held a closed session
  + Questioned NASA personnel from Marshall Space Flight Center and Morton Thiokol
  + Discovered true extent of O-ring erosion
  + Found out that initially Morton Thiokol had recommended /against/ the launch
+ At this point the Rogers Commission switched from oversight to confrontation
  + Requested that no one involved in the decision to launch Challenger participate in the NASA investigation
  + Immediately shifted focus to O-rings as the primary subject of investigation
+ In June the Presidential Commission revealed its report
  + Identified O-rings as the primary cause of the disaster
  + O-rings and zinc chromate putty insulation failed due to unprecedented cold temperatures at launch
  + Combustion gases blew past primary O-ring and impinged upon secondary O-ring, which in turn failed
  + Commission concluded that effects of design, re-usability, temperature and the dynamic loading of the joint combined to cause the joint to fail
  + Also identified organization factors that contributed to the failure
    + Long history of problems at NASA with O-ring joints
    + Documented NASA teleconference described above, where NASA administrators discussed the potential of problems with the SRB joints with Thiokol, but then decided to proceed with the launch anyway, and didn't notify their superiors about the teleconference with Thiokol
  + The Presidential Commission faulted the decision-making process itself rather than individuals
    + Inadequate procedures for reporting problems
    + Faulty information flows
  + However the Presidential Commission failed to answer why NASA managers who did have access to all the relevant information about the O-rings decided to proceed with the launch
+ In October 1986, the U.S. House of Representatives Commission on Science and Technology published a report on the Challenger disaster
  + Echoed many of the findings of the Presidential Commission
  + However the House report placed blame on individuals, rather than the decision-making process
  + Placed blame on NASA and contractor personnel who failed to act to solve anomalies with the SRB (without naming names)
  + Suggested that these personnel were not qualified for their jobs
+ However the facts and narrative in the House report and the Rogers Commission report suggested an alternative explanation: launch schedule pressure

** Pressure To Launch: The Media, The Teacher in Space and The State of the Union
+ In the initial aftermath of the tragedy, many analysts and journalists looked to circumstances unique to the Challenger launch to explain the disaster
+ Initially they focused on the media attention on the Challenger launch
  + Media pressure
    + The previous launch, Columbia had been postponed a record 7 times
    + Every delay had received a lot of attention from the press
    + However, it makes no sense that NASA managers would push ahead with a launch and risk the worst case scenario -- loss of crew and mission -- in response to media pressure
    + In addition, media attention accompanied every shuttle launch -- by this point, NASA should have been accustomed to dealing with media attention
  + Pressure from the Reagan administration
    + The flight of the Challenger had political ramifications
      + Teacher in space was meant to show that space flight was routine enough for the US that even an "ordinary citizen" could go into space
      + State of the Union address was scheduled for January 28, the first night of the Challenger mission, and it was speculated to contain a mention of the Teacher In Space mission
    + However the Presidential Commission found no evidence that the White House contacted NASA to pressure them to launch
    + In addition NASA procedures, in general, did not allow communications hook-ups until at least 48 hours after launch, in order to give the crew time to become acclimated to space
  + Pressure from NASA PR
    + Did NASA PR pressure for a launch, in order to get the Teacher In Space mission included in the State of the Union?
    + However, the Teacher In Space mission was not slated to be in the State of the Union address
    + Even without mention of the Teacher in Space mission, all of NASA's priority items were to be mentioned
    + Moreover if the launch had gone well, the mission would have been a PR coup for NASA, more than compensating for the lack of inclusion in the State of the Union address
    + There was no evidence that NASA engineers or managers responsible for the launch knew about the PR ramifications of a successful launch
+ As it became apparent that Challenger was a typical Shuttle mission, attention expanded to look at pressures on the shuttle program as a whole
  + For NASA, the desire for a positive public image was the result of a continuous struggle for funding
  + The Shuttle had suffered from economic problems throughout its history
  + Economic calculation pervaded every part of the NASA organization
  + Many sources acknowledged that economic strain translated into "production pressure"
  + Commissioner Feynman summed it up by stating that no one had to be told explicitly what to do -- everyone knew the pressures the shuttle program was under and adjusted their decision-making accordingly
  + Implied there was a causal connection between the environment of scarcity and competition and the decision to launch
  + The narrative was that NASA knowingly made a series of cost/safety trade-offs in order to gain secure and maintain funding for the Shuttle program

** The Structural Origins of Disaster: Competition, Scarce Resources and the Shuttle Program
+ From NASA's inception, the space agency played a central role in competition for international supremacy
+ Government was dependent on NASA for military and scientific advances in space until mid-80's
+ Although every administration was concerned about NASA's achievements in space, willingness to fund NASA waxed and waned with changing circumstances
+ NASA secured generous funding from John F. Kennedy as the US was concerned about the political consequences of Laos, Congo, the Bay of Pigs and Sputnik
+ Widespread American concern about the US "falling behind" created an environment of institutional consensus, making NASA the preferred vehicle for national and international prestige
+ With the triple luxuries of generous funding, institutional consensus and a clear goal, NASA rapidly progressed and, in 1969, managed to get US astronauts to the moon
+ However, even before the end of the Apollo program, there were questions being raised about the future direction of the space program
+ The Vietnam War and economic issues displaced the space program as national priorities, with consequent declines in funding for NASA
+ The Space Shuttle was born in this newly uncertain era for NASA, which was bereft of a clear mission after the moon landing
+ In order to justify its continued existence, NASA proposed three missions, whose goal was the long-term presence of humans in space:
  + Mission to mars
  + Space station
  + Space shuttle to transfer crew and cargo from earth to the space station
+ The combination of these three missions was designed to promote national interests and secure NASA's position as a powerful agency
+ However, almost immediately, there was push-back on the basis of cost
+ Post-Apollo funding cuts caused NASA to back off from the Mars mission and the space station and focus on the space shuttle
+ Space shuttle was designed to be a reusable low-cost launch vehicle that would be the nation's sole facility for launching astronauts and satellites
  + /It's so sad, in a way -- the Space Shuttle was trying to be what SpaceX is/
+ Space Transportation System (as the Shuttle was formally called) envisioned a set of "space buses" that would cheaply ferry astronauts and supplies to space, and lay the groundwork for permanent space stations and future space missions

*** Scarce Resources and Compromised Excellence
+ Although NASA was a civilian agency, in order to secure support for the Shuttle, it found it expedient to secure an alliance with the military
+ Positioned the Shuttle as the single launch systems for all payloads, civilian and military
+ NASA and the Air Force struck a deal: in exchange for designing the Shuttle to carry Air Force payloads, the Air Force agreed to support the Shuttle program in Congress and not develop launch capability of its own
+ From the outset, the shuttle was plagued by budget issues
  + NASA called for a shuttle with roughly 10 billion dollars of initial development cost and 2 billion dollars of ongoing costs
  + This was challenged by the Office of Management and Budget, which criticized NASA for designing a "Cadillac" space shuttle
  + However, the cost was necessary because the Air Force required a high-performance launch vehicle
  + In order to determine whether the Shuttle was feasible to build, NASA asked an outside think-tank to research the issue
  + /Mathematica Inc/ determined that the Shuttle would be feasible if it had a launch rate of more then 30 flights a year -- this was considered feasible in 1971 [1]
  + The Mathematica study strengthened NASA's case for building the shuttle, but Congress allocated only half of what NASA requested
+ Design trade-offs: From Cadillac to Camel
  + Power struggles between Congress, NASA, OMB and the White House directly affected the Shuttle design
  + Design process was characterized by trade-offs between development costs and operating costs
  + Trading off development costs for operational costs was justified by the fact that operating costs would be offset by revenue from commercial launches
  + Most initial ideas for lowering development costs involved the use of an expendable booster
  + However, given the large size of the Shuttle this was technically difficult
  + The breakthrough idea was to have a smaller orbiter that could be launched with two reusable Solid Rocket Boosters (SRBs)
  + Both liquid fuel and solid fuels were considered for the booster, but liquid fuels would have higher development cost and lower operating cost, cutting against the grain of the overall Shuttle program
  + In addition, liquid rocket boosters would take longer to refurbish, which would cut into the 30 flights per year that Mathematica set out as a requirement for financial viability
  + NASA's restricted budget necessitated further trade-offs, some apparently trading safety for cost
    + The Space Shuttle was the first NASA launch vehicle without escape rockets
  + The Shuttle program was pulled in contradictory directions 
    + Congress: cost recovery
    + OMB: low development costs
    + Air Force: operational capabilities
    + NASA: Manned spaceflight
  + The final design of the Space Shuttle was characterized as a "camel" -- it was a compromise design that represented the best NASA could do given the constraints it had been given
+ A Bitter Bargain
  + As a result of this compromised design process, NASA, ironically, had to argue for a vehicle that it really didn't want
  + Nevertheless, NASA leaders made the best case they could for the Shuttle
  + Promised 60 flights a year
  + Argued that the Shuttle would attract enough commercial launches to be mostly self-supporting
    + /Pro tip: whenever a government official says that a government program will be self-supporting, they're either deluded or lying/
    + /If it were self-supporting, government wouldn't need to do it/
    + Argued that the shuttle would be able to launch 65,000 pounds per flight at a cost of 100 dollars per pound
    + Argued that higher than forecast operating costs would be offset by a larger number of launches
  + In 1972, President Nixon authorized the development of the Space Shuttle
  + NASA divided responsibility for the Shuttle program as follows
    + Johnson Space Center in Houston got responsibility for the Orbiter
    + Marshall got responsibility for the propulsion system
      + Main engines
      + External fuel tank
      + SRBs
    + Kennedy Space Center got responsibility for final assembly and launches
  + The Shuttle program was funded, but at a cost -- program viability was dependent on the Shuttle being able to meet a launch schedule
  + This built production pressure into the program from its very inception
  + These pressures were compounded by further budget cuts pursued by OMB during the Shuttle's development phase
  + As a result of these cuts, the shuttle fleet had to be reduced from 5 to 4
  + This meant that any potential delays or problems had a much greater impact, because there was much less slack in the system to absorb potential delays
  + In another move to economize, NASA cut safety testing and other quality assurance work
  + The justification for this was that NASA had more experience with manned spaceflight, and thus the extensive and expensive checks of the Apollo program were not necessary
  + Nevertheless, in February of 1979 a National Academy of Engineering panel headed by Eugene Covert (head of Aeronautics and Astronautics at MIT) found that NASA's testing procedures for the Shuttle's main engines were not adequate
  + As a result, NASA altered testing procedures for the main engines

*** Operational Spaceflight: The Shuttle As Business
+ NASA's bargain with OMB and Congress required them to make the Shuttle self-supporting
+ The key to this was to make travel to space on the Shuttle seem "routine" and "economical"
+ In order to do this, NASA emphasized two priorities
  + First, the Shuttle needed to move from being a developmental program to being an operational program as soon as possible
    + An "operational" system is one that is mature and ready for routine use
    + NASA allocated four test flights, upon successful completion of which the program would be declared "operational"
    + The fourth test flight (in 1982) went off without a hitch, and President Reagan and NASA declared the Shuttle "operational"
  + Second NASA emphasized a launch schedule that would both commercial payloads and Congressional approval
    + /I think this is another key mistake. NASA should have realized that commercial payloads and Congressional approval are, to some extent, contradictory demands/
    + /Again, the comparison with SpaceX is telling -- SpaceX went for the commercial market first, and only afterwards did they angle for government contracts/
    + However, the Shuttle was never able to reach break-even
    + In 1976 NASA forecast 49 Shuttle flights in 1984 and 58 flights in 1985, on the way to a schedule of 60 flights a year
    + By the early '80s, however, the projection of 60 flights a year seemed like pure fantasy
    + The 1971 Mathematica study forced NASA to maintain that the Shuttle was a cost-effective program, throughout the entire lifetime of the program
      + /Remember, Diane Vaughan is writing about the Shuttle program up to '86, not the Shuttle program of the '90s and beyond/
    + However, the Mathematica study was based off estimates provided by NASA contractors, who stood to gain valuable contracts if the Shuttle was approved
      + /This isn't as obviously ridiculous as you might think/
      + /Aerospace is a highly specialized field, and there are only a few vendors who have the engineering capacity to build something like the shuttle/
      + /There really isn't an "independent" party that you would be able to ask about the costs of a complex and never-before-tried project like the space shuttle -- everyone who you would ask is going to be a potential bidder/
    + Moreover, the Mathematica analysis underestimated the incremental costs of the program
    + Each shuttle launch added roughly 60 million dollars in marginal costs to a fixed cost of 1200 million dollars (1.2 billion) a year
    + Worse, the quick turnaround time required to achieve 60 flights per year never materialized
    + In 1985, NASA only achieved 9 Shuttle launches, a far cry from the 60 that were originally forecast for that year
    + In addition, the shuttle was never as capable as designed -- the Main Engines did not develop as much thrust as expected, so the actual payload was only 47,000 pounds
+ The shuttle faced unexpected competition, both at home and abroad
  + Companies like ArianeSpace began offering commercial launch services that were cheaper and more reliable than the shuttle
  + Some of the Shuttle's domestic customers, such as NOAA and the Air Force began to pursue independent launch capability, as they became dissatisfied with the shuttle's lack of progress and low launch rates
  + To combat this, NASA engaged in high-profile missions which sought to highlight the unique capabilities of the Shuttle
    + In-orbit satellite repair
    + Satellite retrieval from orbit
  + However these missions only ate up more resources and drove up NASA's cost, further reducing the economic viability of the Shuttle
+ Another way that NASA sought to maintain a positive public image for the shuttle in light of negative publicity was to have flights with people from outside the "traditional" astronaut corps
  + NASA was looking at non-astronaut flights as early as 1976
  + Non-astronaut flight was consistent with two of NASA's long-term goals for space:
    + Permanent occupancy of space by manned systems
    + Participation from ever-broadening walks of life
  + A NASA study team drafted a report called "Unique Personality for Space Shuttle Flights"  which made recommendations regarding the sorts of civilians who would make good candidates for Shuttle flights
  + The initial consensus was for someone from the general area of popular science or a news media personality
  + While sending legislators was considered, this was seen to be fraught with the risk of partisan politics intruding into an otherwise nonpartisan activity
  + While NASA explored the possibility of sending various civilians into space, no definite action was taken until 1984
  + In that year, facing pressure on the issue of education, President Reagan announced that the first civilian passenger on the space shuttle would be a teacher
  + Meanwhile, despite initial recommendations to the contrary, the first civilian passengers aboard the Space Shuttle were legislators
    + In 1985, Senator Jake Garn (R-Utah) and Congressman William Nelson (D-Florida) flew on two separate shuttle flights
    + Both of these legislators were influential on the committees that approved funding for NASA

*** The Widening Gap Between Goals and Means
+ 1985: NASA completes only 9 Shuttle missions
+ Calls for an increase to 24 missions by 1990
+ However, this increase was sought without effective conversion of the Space Shuttle into an "operational" system
+ Although the Shuttle had been declared operational in 1982, the mature, operational system never emerged
+ A mature system failed to develop for two reasons:
  + Personnel were diverted from long-term planning tasks to short term tasks to meet flight schedule needs, ensuring that expertise never developed
  + Budget was never high enough to support the level of development required for the emergence of a mature system
+ NASA was slow to develop the resources necessary to support a mature system
  + During development, all resources were focused on a single shuttle flight
  + During the operational phase, resources were spread across many flights
  + /Again, the contrast with SpaceX is telling: SpaceX, from the beginning, developed its system as an operational system/
  + The attempt to reach 24 flights per year was limited by lack of spare parts, which, in turn caused led to accelerated training schedules
  + Resources became concentrated around short-term problems
  + Spare parts were often cannibalized from future launches in order to unblock the current launch
  + These parts transfers consumed personnel time, created opportunities for damage, and were wildly disruptive to launch schedules
+ Another strain on resources were changes in launch manifests
  + Commercial customers often ran into issues with development, finances or market conditions, which meant that launches had to be rescheduled
  + Because the majority of the work to prepare for a launch occurred in the last three months prior to the launch, last minute changes were extremely costly and disruptive
+ In 1985 Congress cut NASA's funding again
+ By 1985, after accounting for inflation, NASA's budget had been cut by two thirds
+ This sustained scarcity had an increasing effect on the quality of the program
+ The spare parts crisis that led to cannibalization, for example, was a direct result of the budget cuts

** January 1986: Production Pressures and a Disastrous Decision
+ In 1986, NASA was under an enormous amount of stress
+ The problems began, not in 1986, but in 1972 when NASA received the Congressional mandate to build the shuttle without Congress providing funding for the Shuttle
+ Because the Shuttle was justified on the basis of cost-effectiveness, it was evaluated on solely economic criteria
+ Meanwhile NASA was experiencing budget cuts and personnel departures
+ 1986 was a make-or-break year for NASA, with three headline missions scheduled
  + Teacher In Space
  + Astro-1 mission to examine Halley's Comet
  + Missions with the first use of the Centaur cryogenic upper stage from the Shuttle's payload bay
+ The Astro-1 Mission was especially significant, as it was meant to demonstrate the interdependence of manned and unmanned spaceflight, to insulate NASA from detractors who claimed that the Shuttle was taking away from space science research
+ According to post-tragedy analysis, it was a disaster waiting to happen
+ NASA prioritized production over safety
+ The conventional explanation that developed was a "trickle-down" theory
  + NASA was under significant production pressure from outside forces
  + This pressure permeated the NASA organization
  + The production pressure affected decision-making on the eve of the launch
  + NASA managers knowingly violated safety requirements, taking a calculated risk that resulted in the loss of an orbiter and 7 astronauts

* Chapter 2: Learning Culture, Revising History
+ Initially, the Challenger disaster looked like a clear-cut case of organizational misconduct
  + Organizational misconduct: people violating rules in order to further the goals of the organization
  + Presidential commission indicated that NASA had violated industry rules and internal NASA rules designed to guarantee safety
  + These rules were apparently violated in an attempt to increase the launch rate of the Shuttle
+ Three factors associated with organizational misconduct
  + Competitive pressure and resource scarcity
    + Budget cuts and launch schedule pressure
    + NASA intentionally skimped on safety in order to keep the Shuttle flying and meet production goals
  + Organizational characteristics
    + Sprawling web of contractors meant that no one really knew what was going on with the O-rings
    + "Success oriented" culture rewarded managers for correcting the joint temporarily rather than halting flights for a redesign
    + "Transactional" information exchange concealed problems rather than revealing them
  + Regulatory ineffectiveness
    + System regulating the safety of the Shuttle appeared to have suffered a massive breakdown
+ There is ample precedent for this kind of organizational misconduct
  + Many documented in Charles Perrow's book, /Normal Accidents/
  + Ford Pinto: Ford chose to accept the risk of loss of life due to accidents over redesigning the Pinto
  + The difference between mistake and misconduct is /intent/: organizational misconduct has to reflect an intentional breaking of rules and taking on of risk
+ The stereotype of organizational criminality portrays the organization as an amoral profit-seeking enterprise, which rationally weighs the probability and consequences of getting caught violating rules against the benefits that such rule-breaking brings
+ Although NASA is not a corporation, it was subject to many of the same pressures, as it competed against other government agencies for scarce resources
+ As a result, according to conventional narratives, NASA engaged in blatant and intentional rule-violation in order to meet organizational goals and secure resources
+ The Challenger disaster was especially interesting from a sociological standpoint because the extensive documentation and public nature of the tragedy could shed light on the connection between "good" people and "dirty" work
  + Why do educated, law-abiding, well off people violate the law in furtherance of organizational goals?
  + We know that misconduct is associated with competition and resource scarcity, but we don't understand how competition and resource scarcity manifest in individual decisions
  + Data on this question are scarce -- often locked up in internal documents, which may be sealed or destroyed
    + We know which decision were taken, but often we don't have any written reasoning for those decisions
+ While the amoral calculator hypothesis is attractive, there are many reasons to be skeptical of it:
  + Many organizations experience periods of scarcity and competition, and don't violate any rules
  + Organizations violate rules for reasons other than a careful consideration of risks and benefits:
    + Misunderstanding regulatory requirements
    + Incompetence or improper attention to regulations
    + Principled disagreement with regulations
  + Moreover, we know that's not how managers think when making decisions
    + Managers rarely formally calculate risks and benefits, because doing so is often impossible
    + Instead, they weigh a few key considerations, assess the risk that something will go wrong, and then make a judgment call
  + Finally, decision-making doesn't occur in a vacuum
    + Organizations have cultures and values
    + The choices that are available for consideration are constrained by organizational forces
  + The way organizations constrain choice is by establishing norms
    + A norm is a cultural belief or convention that originates in the environment
    + Norms create routine, taken-for-granted scripts that become part of individual world views
    + Norms don't just constrain options, they establish the criteria by which options are discovered
  + Norms are further reinforced by organizational rules on decision-making
    + In most organizations, decision-making is an example of rule-following over calculation of costs and benefits
    + Organizations and individuals are limited in their ability to search for solutions
    + As a result, decisions are made to satisfice, rather than optimize
+ Had NASA administrators acted as amoral calculators, knowingly violating safety rules in order to stick to the launch schedule?
  + Need to demonstrate "macro-micro" connection
  + Show how the macro-structural forces of competitive pressure, organizational characteristics and regulatory ineffectiveness came together to influence individual decision-making
  + Unlike with many other industrial disasters, there was ample publicly available documentary evidence to show not only the decisions that were taken, but also the rationales behind those decisions
+ While initially she believed that the amoral calculator hypothesis was true, after conducting her research, Diane Vaughan's understanding shifted

** Early Affirmation of Amoral Calculation
+ Initially, Diane Vaughan did no interviews
  + Before she could interview, she needed to know what questions to ask
  + In order to ask productive questions, she needed to be familiar with the cast of characters and the technical and bureaucratic language needed to have an intelligent conversation about the Challenger
  + The main primer for her research was Volume 1 of the Presidential Commission, published in June 1986
  + Although the Presidential Commission report was published for a lay audience, it was still tough reading
+ As she studied the event in more detail, Diane Vaughan realized that some of her initial assumptions regarding the Challenger disaster were incorrect
  + Challenger did not explode
  + There was a fireball and a structural failure, but no explosion
  + Also, the dramatic public demonstrations that Commissioner Feynman gave dramatically oversimplified the issues discussed on the prelaunch teleconference
    + Everyone knew that rubber gets hard when it gets cold
    + The issues discussed in the teleconference involved matters of joint dynamics, joint rotation and ignition pressure, with millisecond-level timing
+ However, as her initial misconceptions were corrected, she developed new ones
  + For a while Vaughan was convinced that the O-rings were like Nerf balls, sitting in the booster field joints
  + However, the O-rings were more like very long strings of very thin licorice, that sat in the field joints
  + It was difficult to comprehend the scales involved
    + On a booster the size of the Statue of Liberty, the field joint gap in question was 0.004"
    + When enlarged, the gap increased to somewhere between 0.0042" and 0.006"
    + The expansion occurred for 0.6 seconds, right at the beginning of the launch
+ Although her understanding of technical issues changed, the evidence seemed to reinforce initial impressions of amoral calculation
+ NASA management actions on the eve of the launch
  + Commission confirmed that NASA managers at Marshall played a major role in convincing Thiokol to reverse its recommendation to delay the launch
  + According to Thiokol, Marshall flipped the burden of proof -- made it incumbent upon Thiokol to show that the launch would be unsafe
  + It was also unusual that managers at Marshall requested Thiokol to send them written confirmation of their recommendation to launch
  + This was initially seen as a possible indication that NASA managers at Marshall wanted written confirmation in order to show that they were proceeding on advice from Thiokol
  + The Presidential Commission also found apparent evidence of rule-breaking on the eve of the launch:
    + NASA rules specified that NASA managers who knew about technical problems needed to transmit those problems up the hierarchy
    + In this case, however, higher-level NASA administrators were not informed about the teleconference
  + The failure to transmit information about potential problems with the O-rings up the management chain appeared to be a blatant cover-up
+ Previous cost/safety trade-offs
  + NASA had a history of decision-making in which economic considerations seemed to take priority over safety
  + Reinforced suggestion of an organization culture where amoral calculation was the norm
  + 2 incidents stood out
    + Decision to eliminate the escape rockets
      + Increased payload capacity
      + However left the astronauts with no way to escape if there was a catastrophic failure early in the flight
    + Decision to award the SRB contract to Morton Thiokol
      + Although Morton-Thiokol Wasatch had previous experience designing solid rocket boosters for the Trident and Minuteman missiles, they were not seen as a leader in the field
      + Thiokol won the contract to build the SRBs even thought its design was ranked lowest out of the 4 submitted
      + James C. Fletcher, who was the NASA administrator at the time, announced publicly that the rationale for the decision was cost -- Morton-Thiokol's bid was about $100 million lower than the competition
        + Fletcher was later found to have deep political and personal ties to Utah, where Thiokol was based
        + Shuttle contract was a huge financial windfall for Morton-Thiokol and resulted in the creation of 6,500 jobs and Shuttle spending accounted for 44% of Morton-Thiokol's aerospace revenues in FY 1985
  + It seemed apparent that NASA had started building the Shuttle on the cheap
  + Even when there were problems, the solution was never to stop flights and redesign the SRB field joints, but rather to tinker with the existing design
  + A redesign could take up to two years, and would be enormously expensive
  + Moreover, revenue from all the launches during these two years would be deferred or lost entirely
+ Cover-up
  + Adding to the perception of amoral calculation was the apparent cover-up of Shuttle-related information at the time of the accident
  + NASA impounded all documents related to the disaster
  + NASA began its own investigation, conducting it in "great secrecy"
  + Furthering impressions of a cover-up was the way that NASA handled the recovery of the crew's remains
    + NASA's initial transcript of the tape recovered from the Challenger wreckage showed that the last words were Commander Richard Scobee's "Go at throttle up", which implied that the crew had been killed instantly by the fireball and violent break-up
    + However a report released 11 days later said that the last words on the tape were "Uh oh", which indicated that the crew may have been aware that something was going wrong
    + Recovery of the crew's remains took six weeks, and questions were raised about why it took so long, when debris from the crew compartment had floated to the surface a month after the disaster
    + Analysis of the recovered oxygen packs and the footage of the shuttle's breakup showed that the crew may have been alive until the crew compartment hit the water
+ Young, Boisjoly, Cook and Feynman
  + Further credence to the amoral calculation hypothesis came from
    + Veteran astronaut John W. Young
    + Thiokol engineer Roger Boisjoly
    + NASA resource analyst Richard Cook
    + Presidential commissioner Richard Feynman
  + Cook was responsible for assessing the budgetary impacts of the external tank, SRBs and Centaur upper stage
    + Wrote a memo in 1985 that indicated that flight safety was being compromised by the potential seal failure
    + Indicated that personnel knew of the possibility of failure and understood that failure would result in catastrophe
  + John Young was chief of NASA's astronaut office
    + Wrote on March 4 1986 that "some crews were lucky to be alive"
    + Alleged that the only reason the Shuttle had flown with such a flawed design was because of launch schedule pressure
    + Enclosed a list of other design elements of the Shuttle that were allegedly compromised due to the same factor
    + Noted that safety and flight schedule are conflicting goals and that safety didn't win when it was placed against schedule pressure
  + Roger Boisjoly brought civil and criminal charges against Thiokol
    + Charged that Thiokol had knowingly supplied NASA with defective solid rocket motors
    + Alleged that Thiokol had fraudulently signed off on the motors prior to Challenger's final launch
    + Charged NASA with collusive action based upon economic interest
    + Said that people at NASA and Thiokol knowingly withheld information about problems with the solid rocket boosters in order to meet production concerns
  + Richard Feynman -- Nobel Prize winning physicist on the Presidential Commission investigating the Challenger disaster
    + Claimed that NASA was playing "Russian Roulette" by going ahead with launches when they knew that there were issues with the boosters
    + Suggested that successful launches caused NASA administrators to knowingly downplay the risk, even though they knew that were outstanding issues
  + Together, these four individuals painted a picture of intentional managerial wrongdoing
  + Supported stereotypes from theories of organizational misconduct and amoral calculation

** Puzzles and contradictions
+ The hypothesis set out by the investigative commissions in the aftermath of the Challenger disaster is that safety rules were /knowingly/ violated in order to stick to the launch schedule
+ In order to prove this hypothesis, we need to show how the economic pressures affected managers' actions
+ However, the Presidential Commission never asked specific questions about the connection between economic strain and managerial actions
+ Therefore, the evidence, while apparently strong, was still circumstantial
+ Furthermore, as she did more research, Vaughan found evidence that contradicted or added missing context to many of the statements which led many to believe that the launch was the result of organizational misconduct
+ The documents that the early public narratives relied on systematically distorted the public impressions of NASA actions
+ NASA management actions on the eve of the launch
  + The basic assumption of the amoral calculator hypothesis is that the launch was the result of a cost/safety trade-off
  + This posits costs and safety as competing goals, and suggests that satisfying one reduces one's ability to satisfy the other
  + While this applies to many decisions taken at NASA, it doesn't seem to apply to the decision to launch the Shuttle
  + In the decision to launch, safety and economic considerations are interdependent rather than competing goals
  + Key to the amoral calculator's decision-making is the probability of /detection/, and the costs of getting caught
    + For NASA, SRB failure during launch would be immediately detectable
    + The costs would be instantaneous and catastrophic
    + The manned space program was already in parlous shape -- a failure might lead to the administration giving up on manned spaceflight altogether
  + If NASA managers knowingly launched /Challenger/ after weighing the costs of potential failure against production pressures, how could they fail to take into account the extensive costs of an O-ring failure
  + If NASA was so keen to convince the world that spaceflight was routine and economical, why would they risk failure on the first mission in which an "ordinary person", Christa McAuliffe, was scheduled to fly?
  + In a broader sense if NASA was facing pressure from its customers to launch payloads, why would it risk losing those payloads by launching them on a booster that it knew to be flawed?
  + To argue that NASA managers knowingly launched /Challenger/ as the result of an amoral calculation is to suggest that decision-makers acted in opposition to NASA's commercial interests, rather than in concert with them
    + /Well, this argument can be made -- you can argue that the decision to launch was the result of principal-agent problems/
    + /Everybody assumed that it was someone else's job to assure safety, and, as a result, safety was ignored as everyone pursued their own narrow interests/
  + Another thing that is often missed is that none of the engineers opposing the launch were calling for the launch to be canceled
  + They were arguing for delay
  + It doesn't make any sense that NASA would risk catastrophe for a few hours of schedule
+ Previous cost-safety trade-offs 
  + Previous examples of cost-safety trade-offs identified by the press and astronaut John Young cannot serve as automatic verification that the decision to launch /Challenger/ was the result of a cost-safety trade-off
  + Be careful of the retrospective fallacy -- it's easy to cherry pick particular instances that look like cost/safety trade-offs, when in reality NASA made thousands of decisions each day re: the Shuttle and some are bound to look like cost/safety tradeoffs in retrospect
  + Every decision has a cost component, because resources are finite
  + It's easy to see the risk associated with certain decisions in hindsight
  + Contradicting the narrative of cost/safety trade-offs, the Presidential Commission report is replete with examples where NASA managers accepted higher cost as the price of maintaining safety
    + System of checks and balances between different parts of the organization
    + Extensive checklists and procedures
  + In order to show that NASA had a "pattern" of cost-safety tradeoffs, you'd need to look at all NASA decisions and understand how the safety and economic issues were evaluated by management at the time the decisions were made
  + Two examples of decisions that became controversial in retrospect (/from Appendix A/)
    + Early design decision to eliminate the escape rockets
      + Was not controversial at the time that it was made
      + History of decision
        + NASA's choice of SRBs for the space shuttle had safety implications
        + SRBs can't be shut down in an abort scenario
        + As a result, the initial design of the Shuttle featured escape rockets to allow the crew capsule to separate from the launch vehicle during the first two minutes of flight
        + However, the large size of the orbiter meant that escape rockets powerful enough to separate the orbiter from the SRBs would weigh more than the payload
        + The escape rockets were scrapped, as part of an overall weight-saving drive in the design
      + After the disaster, this decision was cited as an example of the priority placed on commercial success (prioritizing payload over safety)
      + However, this interpretation is incorrect
      + The decision to scrap the escape rockets to save the crew was accompanied by a full exploration of all possible first-stage crew escape systems
      + It was found that any method of ejecting the astronauts from the orbiter would fail because the astronauts would be pulled into the flame behind the boosters
      + And if there was a joint failure that caused the SRB to blow up on the ground, there wouldn't be sufficient warning to activate the escape rockets
      + /But doesn't this validate the point? Sure, the *specific* decision to scrap the escape rockets may not have been the result of cost/safety trade-offs, but the overall design that made escape rockets infeasible was/
      + NASA's design rationale was that it was safer to do the work to design the first stage ascent to be as safe as possible than to spend time, money, and payload capacity on escape rockets
        + "No known measurement parameters that would forecast, with sufficient action time, a pending catastrophic event requiring abort"
        + The only indication of failure is the failure itself
        + No practical means available that would result in a meaningful increase in crew survivability during the first-stage ascent
      + In NASA's judgement, escape rockets could not have saved the crew anyway, so eliminating them lightened the orbiter with no safety trade-off
      + The House Committee on Science and Technology also reviewed this decision and agreed with NASA's analysis
    + Controversial awarding of SRB contract to Thiokol (segmented vs. monolithic)
      + In contrast to the escape rocket decision, the decision to award the SRB contract to Morton Thiokol was extremely controversial, both at the time the contract was awarded and after the /Challenger/ disaster
      + One of the alternative proposals for the SRB design was a monolithic SRB proposed by Aerojet
      + After the /Challenger/ disaster, the choice of a segmented booster was cited as a cost-safety tradeoff
      + The document cited to justify the judgement of the segmented booster being the result of a cost-safety tradeoff was a 1973 report to the Source Evaluation Board, which assessed the 4 proposals submitted for the SRB contract
      + Aerojet's proposal specifically cited the potential failure modes of a segmented booster as a reason to choose a monolithic SRB
      + However, of the four proposals submitted *only* Aerojet submitted a monolithic design
      + In addition to Thiokol, Lockheed and United Technologies also submitted segmented designs
      + NASA's SEB evaluated all for proposals on the following criteria:
        + Design, development, and verification
        + Manufacturing, refurbishment and product support
        + Management
      + The evaluation ranked Lockheed's proposal (/a segmented design/) the highest and Thiokol's the lowest
      + The text of SEB report, however, stated that the problems with Thiokol's design were all minor and could be readily fixed
        + /The report was wrong -- the flaws were not minor and could not be readily fixed/
        + /However, this is not a case of a cost-safety tradeoff, this is a case of design problems being difficult/
      + More pertinently, Aerojet's proposal was ranked significantly below the others on the Mission Suitability score
        + Strength of the case was found to be inadequate for pre-launch loads
        + Not designed with an adequate safety factor for water-impact
        + Proposal included the use of unspecified ablative materials in the nozzle (/translation: Aerojet's design required the use of unobtanium/)
        + Propellant was not sufficiently tested -- NASA was not confident that Aerojet's propellant would deliver the required thrust
        + While a monolithic SRB may have been superior in principle, in practice, Aerojet's proposal was inadequate on a number of metrics
      + The decision to award the contract to Thiokol was double-checked by an outside party
        + When NASA awarded the contract to Thiokol, Lockheed filed a bid protest with the Government Accountability Office
        + This caused the GAO to conduct its own independent investigation
        + The investigation reassessed both the technical and costs aspects of the Lockheed and Thiokol designs
        + The GAO report confirmed
          + The choice of segmented rocket boosters would not sacrifice performance or safety
          + Agreed with NASA's assessment that the flaws in Thiokol's design were not major and were readily correctable
        + Noted that even after corrections, Thiokol's proposal was $56 million cheaper than Lockheed's
        + In light of this, GAO left it to NASA's discretion to reconsider the decision, and NASA chose to remain with Thiokol for the SRBs
      + This evaluation was confirmed in interviews with Leon Ray, a Marshall Space Center engineer who sat on the SEB that evaluated the booster designs
        + Lockheed's design was thought to be better in theory, but wasn't proven
        + Thiokol's design was based on an existing rocket -- the Titan III rocket, which was seen as one of the most reliable rockets ever built
  + NASA didn't consciously trade off cost and safety -- instead, NASA engineers and managers made decisions to satisfice cost and safety requirements based upon the best available information they had at the time
+ Cover-Up
  + The cover-up cannot constitute evidence about the Challenger launch decision, since it took place chronologically after the disaster
  + All organizations seek to control their public image and the desire to do so only increases in the face of a tragedy
  + NASA's impounding of Challenger flight data was not part of a cover-up but was standard operating procedure in the aerospace industry
  + NASA administrators seemed to vaccilate about the technical cause, even though there was evidence implicating the SRB as early as two days after the disaster
    + NASA administrators wanted to allow the full fault analysis to complete
    + Not all evidence is what it seems at first glance and NASA administrators judged it best to complete their analysis rather than go back and forth on the "true cause" of the disaster
  + The difficulty in getting data out of NASA after the Shuttle disaster was due to organizational chaos inside the organization
    + Although NASA had procedures for impounding data after a disaster, there were no other procedures in place
    + Compounding the problem, NASA administrator James Beggs was on a leave of absence, and in his place was William Graham, a policy analyst with no experience running a major technical organization like NASA
  + Compounding this was the massive amount of documentation around Challenger
    + The Challenger documents fill a two-storey warehouse
    + At the time of the disaster, these documents were scattered around the NASA bureaucracy
    + Even as late as 1992, more documents related to Challenger were still being catalogued and sorted
  + One thing that does support a cover-up theory is NASA's reluctance to make available cockpit recordings
    + NASA defended this as an attempt to protect the privacy of astronauts' families
    + In contrast to the rest of the disaster response, NASA's response with regards to the Challenger crew seemed to be a well-organized, politically sensitive operation designed to conceal rather than reveal
  + To generalize the term "cover-up" to encompass all incidents in which information was slow in coming is mistaken, because there were a number of reasons for why information was slow
+ Young, Cook, Boisjoly and Feynman
  + No one accused any of the NASA managers involved in the Challenger Launch Decision of being an amoral calculator
  + Though the Presidential Commission documented many cases of economic pressure on NASA, no individuals were confirmed or even alleged to have placed economic considerations ahead of crew safety
  + Even Roger Boisjoly, a whistleblowing engineer, was stymied when asked why NASA engineer and managers would, as a result of production pressure, vote to go ahead with a launch that had the potential to stop production altogether

** Rule Violations
+ The first goal of a case study is to find out what you have a case of
+ If the Challenger Launch Decision were really a result of amoral calculations, there ought to be rule violations
+ In order to determine whether there were rule violations, we look at the following decisions
  + The Criticality 1 Waiver
    + In 1982, Marshall assigned the SRB joints a "Criticality 1" status, indicating that the joints were not redundant, as the design required
    + However, just after the "Criticality 1" status was assigned, a waiver was issued by Lawrence Mulloy, allowing the subsequent launch to proceed
  + The Launch Constraint Waivers
    + In 1985, after extensive joint erosion was reported, NASA imposed a "Launch Constraint" on the SRB joints
    + A Launch Constraint indicates a serious safety issue that justifies canceling a launch
    + However, Lawrence Mulloy also waived the Launch Constraint, allowing the subsequent 5 launches to proceed without the joint problem being fixed 
+ At first glance, the Criticality 1 and Launch Constraint waivers represent clear evidence of amoral calculation
+ However, these waivers were not rule violations -- interpretation resulted from a misunderstanding of NASA's bureaucratic language
+ In the context of NASA, a waiver is a "formalized procedure that, upon approval of the technical rationale behind the request, allows an exception to some internal rule"
+ Waivers were common at NASA
  + If waivers were the result of amoral calculation, it doesn't make sense for them to be recorded rather than covered up
+ Criticality 1 Waiver and Launch Constraint Waiver were the result of different procedures
  + Although the Presidential Commission report uses the term "waiver" to describe both procedures, that's not how the internal NASA documentation describes them
  + With regards to Launch Constraints, NASA reports use the word "lifted"
  + Further investigation showed that the imposition and lifting of Launch Constraints was also a matter of routine bureaucratic procedure at NASA
+ The interesting thing is that NASA had rules that allowed one to bypass other rules
+ As a result, what would appear to be rule violations to an outsider were, to a participant, the result of standard operating procedure
+ Where one would expect rule violations, one found only conformity

** From Current Event To Historical Ethnography
+ Two controversial actions that NASA outsiders had described as deviant were not deviant to insiders
+ Actions are never deviant in and of themselves -- deviance can only be posited in response a particular set of group norms
+ Commissions analysis of apparent rule violations was central to the accepted historical narrative around Challenger
+ However, the Commission didn't understand NASA terminology and procedures
+ Mistakenly identified C1 Waivers and Launch Constraint Criteria "waivers" as violations
+ Failed to compare decisions made with regards to the SRB with decisions made regarding other Shuttle components
+ In order to determine the true cause of the tragedy, we need to understand NASA culture
+ In order to understand NASA culture, we need to look at the actual documentation of the Challenger launch decision
  + Interviewing, at an early stage is likely to be a waste of time -- won't know what questions to ask
+ The 5 volume Presidential Commission report gave a good view into NASA's culture prior to the disaster
+ According to the report, industry standards had been violated in the design of the Shuttle -- were these the true rule violations?
+ What was the role of competitive pressure?
+ How did competitive pressure not only shape the response to the rules, but also the rules themselves?
+ By the time Diane Vaughan was done reviewing the Presidential Commission report, the House Science and Technology committee had released its own report
+ Once again, she was struck by how decisions that appeared deviant to outsiders were in fact normal to insiders
+ Instead of focusing on rule violations, Vaughan expanded her analysis to all decisions that were made regarding the SRBs for the period of 1977-1985
+ The work became a historical ethnography -- attempt to elicit organizational structure and culture from documents created prior to an event
+ Apply the tools of the social historian and anthropologist to a thoroughly modern setting
+ The most significant findings of the ethnographic approach were the following
  1. A 5-step decision-making process in which deviation of the SRB from predicted performance was redefined as an acceptable risk
     + The dominant belief about the SRB joint was that it was safe to fly
     + Although there existed differences of opinion about what to do about the deviation from expected performance all parties agreed that the joint was flight-ready
  2. Decision-making in the SRB work-group conformed to NASA rules
     + Post-tragedy accounts stated that NASA managers ignored engineers and violated safety rules
     + Instead what Diane Vaughan found was that managers depended on engineers for risk assessements
     + Far from suppressing information, NASA managers conformed to NASA regulations about what information should be passed up the hierarchy
+ The attention to rule violations deflected attention from the fact that NASA managers and engineers alike had developed a worldview that allowed them to carry on as if nothing was wrong, even when faced with continual evidence that something was wrong
+ This is the problem of /normalization of deviance/
+ Three factors explain normalization of deviance
  + Work group culture
  + Culture of production
  + Structural secrecy

** Risky decisions and the normalization of deviance at NASA
+ Risk is not a fixed attribute of an object
+ Risk is constructed by individuals from past experience and present circumstances
+ Example: a professional butcher does not see the same level or risk in a carving knife as a parent catching their toddler reaching for the same type of knife
+ From their assumptions, expectations and experience, individuals construct a worldview, through which they assess risk
+ Worldviews tend to become self-confirming, because people tend to seek out confirmatory evidence and avoid contradictory evidence
+ People push aside contradictory evidence until they encounter something "too fascinating to ignore, too clear to misperceive, too painful to deny, which makes vivid still other signals they do not want to see, forcing them to alter and surrender the worldview they have so meticulously constructed"
  + /Meta-note: that's just some beautiful phrasing right there/
+ Under conditions of uncertainty the potential variation in levels of risk assessment grows even more
+ Organizations creating potentially hazardous technical artifacts have a responsibility to determine not just whether risk is present, but how much risk
+ Experts are not immune to the power of worldview
+ On the contrary, due to their training and experience, experts can have a false confidence in their own beliefs even as those beliefs are influenced by their worldview in powerful and unacknowledged ways

*** The production of culture, the culture of production and structural secrecy
+ A /culture/ is a set of solutions created by a group of people to meet specific problems that they face in common
+ These solutions are passed on as the rules, rituals and values of the group
+ It's a fallacy to assume that groups have a single culture
  + Small groups have a single culture
  + Most organizations, however, are segmented and have potentially as many cultures as subunits
  + Cannot be assumed that those cultures are linked to each other or to the larger organization
  + Although some uniform values may permeate the entire organization, it remains to be seen how far those values permeate any given subunit
+ Rules rituals and beliefs (i.e. culture) may arise in work-groups, apart from formal organizational sub-units
  + Work group: people in an organization who interact because they have a particular task in common
  + An organization may have many work groups that cross-cut its internal organization
  + While work group culture may be far from harmonious, work groups do form certain ways of thinking about the problem that they are attempting to solve that form a culture
  + The work group's culture informs the worldviews the participants bring when the interpret information
+ How did work group culture inform the decision to launch the Challenger?
  + Early on in the Shuttle program, there was evidence of deviance in the performance of the SRB joint
  + This led to the following sequence of events:
    1. Signal of potential danger
    2. Official act acknowledging escalated risk
    3. Review of evidence
    4. Official act indicating normalization of deviance: accepting risk
    5. Shuttle launch
  + The SRB work group normalized the deviant behavior of the SRB joints
    + Deviant behavior was initially noticed
    + This behavior was reinterpreted as within the acceptable norm for joint behavior
    + Then the behavior was labeled an acceptable risk
  + By this process the SRB work group redefined evidence that deviated from the previously accepted standard so that it became the standard
  + The method of dealing with the SRB joint deviance established a precedence
    + Problem is not serious
    + Solution is to correct the existing design rather than redesign the joint
  + This pattern of decision making repeated itself whenever there were further problems with the SRB joints
+ What was the basis by which the SRB work group culture rationalized its decisions?
  + The work group believed the joints had redundancy
  + Unless there was erosion by hot gases, the primary O-Ring would seal the joint
  + Even if the primary failed, the secondary would seal the joint
+ Although there was certainly dissent, all participants in the work group thought the SRB joints were an acceptable flight risk
+ Even in 1985, when there were further signals of danger that promoted NASA to invest in a redesign, the work group (including the Thiokol engineers who voiced objections in the pre-launch teleconference) continued to recommend launching with the existing joint design
+ The above 5-step process illustrates /how/ deviance was normalized, but doesn't tell us why
  + We know that organizations, NASA included, are capable of identifying and correcting technical problems
  + Why didn't that capability come into play with the SRBs?
    + Culture of production
      + Environmental contingency that affected the SRB work culture
      + Norms and beliefs originating from
        + Aerospace industry
        + NASA
        + Culture of Marshall Space Center
      + Legitimated work group decision-making
    + Structural secrecy
      + Patterns of information
      + Organizational structure
      + Regulatory relationships
      + These made it difficult for people outside the SRB work group to see what was going on inside the work group, making it more difficult for outside parties to weigh in on the SRB joint issues
+ The work-group's culture established a worldview in its participants that held that the SRB joints were an acceptable flight risk, even though there was data to the contrary
+ There is a paradox in the power and powerlessness of the SRB engineers
  + They were the ones who established this worldview
  + But they were also powerless to overturn this worldview when contrary information came in
  + Were unable to contradict themselves after having repeatedly affirmed to themselves and others their belief in redundancy
+ Challenger /is not/ an example of amoral calculation
  + Managers were moral and scrupulously rule-abiding
  + Production pressures exerted a powerful influence, but that influence was /below/ the level of rational thought
+ The true tragedy of /Challenger/ is that everyone did their jobs, honestly, morally, and to the best of their ability and /because/ of that a tragedy occurred

** Retrospection and History
+ Organizations have failures more often than we suspect
+ Usually these failures are caught and corrected by another part of the organization
+ Only when failures create negative consequences that are publicly defined as failures do we stop to consider the causes of failures
+ This opens us up to the distorting influences of retrospective analysis and hindsight bias
+ Problems that were ill-structured before a disaster tend to become well-structured after a disaster, as people go back and reinterpret ambiguous data in light of what happened
+ Post-tragedy accounts extracted a coherent set of signals from an incoherent stream of data
+ This resulted in a systematic distortion of history that, by taking events out of context, did not show events as the people experiencing those events would have seen them /at the time/
+ This distortion was a necessary result due to:
  + There being an enormous amount of data
  + Analysts having limited time to sift through data
  + The necessity of simplifying and creating a narrative to inform non-technical readers
+ Chief among these retrospective narratives was the Presidential Commission report
+ The report, in Volume 1, repeatedly states, "NASA did this," or "NASA did that", simultaneously blaming everyone and no one for decisions
+ While the report does not blame any individuals, their televised questioning of NASA middle managers and the erroneous finding of rule violations in the decision-making leading up to the launch created the impression that NASA middle managers were solely to blame for the tragedy
+ The Presidential Commission did not fully grasp NASA's reporting rules, so it states that information was suppressed when in fact it was transmitted using the correct channels
+ The selection of witnesses underrepresented working engineers and overrepresented dissenters from the decision to launch
  + Only 7 engineers were asked to testify and they had all opposed the launch
  + However, there were 15 engineers on the pre-launch teleconference
  + The focus of the questioning was on the specific decision to launch, so the questioning of the "dissenters" overlooked the fact that many of them had originated the engineering analyses that justified the launch, and which they were now dissenting against
+ While the Presidential Commission report was 5 volumes in total, most people focused on the summary (Volume 1) and the televised hearings
+ As a result people siezed on whatever findings in Volume 1 allowed them to explain the tragedy and moved on
+ Most of these explanations involved some variant of the "amoral calculator" hypothesis
+ Although the House Science and Technology Committee report contradicted many of the findings of the Presidential Commission report, it never received the same level of attention as the Presidential Commission report, and so was unable to challenge the narratives that the Presidential Commission report fostered
+ As a result, the widely accepted narrative regarding Challenger is that the decision to launch was the result of an amoral calculation by middle managers who intentionally violated NASA rules

** A Revisionist Account
+ This book challenges that narrative
+ Two questions:
  + From 1977 to 1985, why did NASA continue to launch with a SRB joint design that it knew to be flawed?
  + Why did NASA launch Challenger when the engineers who were closest to the joint were opposed?
+ 

* References
1. [[https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/19730005253.pdf][Mathematica Report on the viability of the Space Shuttle]]
