#+TITLE: Managing Risk: Nuclear Weapons in the New Era of Geopolitics
#+OPTIONS: num:nil

* Introduction: The New Nuclear World Order
+ Bruce Jones:
  + For the past two decades, governments and observers have paid more attention to nuclear non-proliferation than to the more traditional concerns of deterrence, strategic stability and arms control
  + These concerns are once again coming to the forefront with the new era of great-power competition
  + Discuss the intersection of strategic stability and non-proliferation -- these two concerns don't always align
  + Discuss whether the US government is well-positioned to handle contemporary challenges posed by nuclear weapons
+ Frank Rose:
  + For the past 25 years, our nuclear policy has been about reducing the number of nuclear weapons
  + We are now probably at the end of that process and we won't be talking about reductions for some time
  + How do we manage great power competition with Russia and China
  + Nuclear deterrence is necessarily a part of this competition
  + Nuclear modernization is a components of deterrence
  + Keep in mind the /real goal/ of arms control: prevent nuclear war
+ Strobe Talbott:
  + Examine deterrence and arms control together
  + "Classical" approaches to arms control are obsolete
  + Evolution of Russia's strategy has made the old discussions around arms control obsolete
+ Robert Einhorn:
  + Stability has to take priority over reductions
  + Prevailing framework is out of date
    + Prevailing framework was focused on bilateral deals between the USA and the USSR
    + Provide for equal numbers of nuclear weapons on equal numbers of 3 types of delivery vehicles:
      + ICBMs
      + Land-based missiles
      + Strategic bombers
      + /Surprised that he doesn't mention submarine launched missiles, but perhaps that's because submarine-launched missiles weren't subject to arms control treaties?/
      + /Submarine-launched missiles *are* covered by arms control treaties, both directly and as a result of limitations on numbers of warheads and delivery systems/
      + /Maybe he misspoke, and meant submarine-based missiles instead of land-based missiles/
  + 2 things have made this old framework obsolete
    + Emergence of China as a near-peer great-power competitor
    + Advent of new offensive and defensive systems
      + Missile defenses
      + Long-range high-precision conventional strike systems
      + Anti-space systems
      + Cyber-warfare
    + /Adversaries now have credible *non-nuclear* ways to cripple their enemy's ability to launch a retaliatory counterstrike/
  + We need to think about many more variables when considering arms control and strategic stability
+ Madelyn Creedon:
  + Some of this is due to natural forces of economics and politics
  + At the end of the Cold War, it was clear that neither the US nor Russia *needed* as many nuclear weapons as they had
  + Russia's dire economic straits created an opportunity where Russia was willing to negotiate arms reduction
    + /They gained directly by having fewer weapons to maintain, which was an important concern, given how many weapons they had and how much maintenance nuclear weapons need/
  + US, meanwhile, was focused on terrorism rather than great power conflict
    + /Allowed the US government a freer hand on negotiating arms control because the US public and US politicians were more focused on the threat posed by transnational terrorism -- didn't seem as important for the US to maintain an unassailable lead in nuclear weapons/
  + The new environment is a result of states wanting better, not necessarily more, nuclear capability
    + Russia needed a credible nuclear arsenal in order to be taken seriously as a world power, and it began to modernize its weapons as soon as it had the money to do so
    + United States had a series of unfortunate incidents which brought to light how badly its nuclear arsenal had deteriorated in the post-Cold War era
    + China needed a more credible nuclear deterrent in order to exert more influence in its region
      + /Remember, unlike the US, China has *two* nuclear states bordering it: India and Russia/
      + /The US nuclear arsenal would get a lot more attention too, if:/
        1. /Canada and Mexico were both nuclear armed powers/
        2. /They had expansionary geopolitical ambitions of their own/
  + We need to worry about the qualitative capabilities of nuclear weapons, not just absolute numbers (/like "throw weight", or numbers of delivery vehicles/)
+ Frank Rose:
  + Thomas Schelling, in the '60s, wrote about how the "character" of weapons mattered, in addition to the numbers of weapons
  + We can no longer used the "two-states/one-weapon" paradigm when discussing arms control
    + /Two states: US and USSR/
    + /One weapon: ICBMs/
  + Today, we need to think about not just the US-Russia relationship, but the US-China relationship, the Russia-China relationship, the India-Pakistan relationship...
  + Meanwhile, the introduction of new technology means that we can't discuss arms control solely in terms of a single weapons system
  + /Can't just talk about how many ICBMs we have vs. how many they have/
* Arms Control
** Russian Resurgence
+ Bruce Jones: Given Russia's modernization and its threats to explicitly use nuclear weapons, how should the US approach the bilateral nuclear relationship with Russia?
+ Michael O'Hanlon:
  + Nuclear stability depends on great-power stability
  + The only way that nuclear weapons become safe is if the great powers outline which domains they're going to compete in and which domains are off limits
  + Russia's nuclear threats are in service of other goals
  + The Russian government is not interested in pursuing a nuclear stability strategy for its own sake
  + They're willing to violate arms control treaties if they think it will serve their broader strategic objectives
  + It is a mistake to think that everyone is after nuclear stability
+ Frank Rose:
  + Nuclear weapons are critical to Russian geopolitical strategy
  + Russia has no real allies, other than maybe Syria and Belarus
  + Demographic challenges
  + Economy that is still dangerously dependent on commodities and resource extraction
  + While they have modernized their military to some extent, their military still lags far behind the US, especially in its ability to operate globally
    + /For example, look at all the problems they had with their sole aircraft carrier when they attempted to perform combat operations in Syria/
    + /There were so many issues that the airplanes were transferred to a land base, and the carrier sailed back to Russia, empty/
    + /Meanwhile the US routinely conducts combat operations from two or three carriers at the same time/
  + The Russian "strategic partnership" with China is solely about balancing the US
  + Nuclear weapons are the only thing where the Russians can credibly claim that they are the equals of the US
  + What are the geopolitical implications for the US?
    + Russia does not believe that the European security infrastructure that was built up in the '80s and the '90s is in its interest
    + View that arms controls treaties were imposed upon Russia when it was weak
    + /Shades of German dissatisfaction with the Treaty of Versailles/
    + Russia has a different view of bilateral nuclear treaties than the US
      + Treaties are about ensuring that they maintain parity with the US
      + What the treaty bans and does not ban gives Russia insight into our nuclear strategy and our technological capabilities
      + /Anecdote time:/
        + /Payne, in _The Great American Gamble_, talks about how the Russians were absolutely baffled when the US proposed ABM treaty banning missile defense research/
        + /The Russians considered US missile defense capabilities to far superior to their own, and could not understand why the US would throw away the possibility of a decisive strategic advantage/
        + /Of course, that didn't stop them from signing the ABM treaty/
+ Bruce Jones: What role does Russia play in the North Korean and Iranian proliferation efforts?
+ Madelyn Creedon:
  + With regards to North Korea, Russia plays a disruptive role
  + Not viewed as a major player by Pyongyang
+ Suzanne Maloney:
  + With regards to Iran, it's the US that's the disruptor
  + Russia played a crucial role in negotiating the JCPOA and continued to participate productively in those negotiations even as US-Russia relations deteriorated elsewhere
  + It is in Russia's interest to appear to be the more reliable partner after the US walked away from the JCPOA deal
    + Deepen ties with both Iran and Syria
    + Simultaneously benefit from higher oil prices due to reductions in Iranian exports due to US sanctions
+ Robert Einhorn:
  + Russia genuinely does not want Iran to have nuclear weapons
  + Russia also has a commercial interest in being able to sell nuclear reactors and fuel to Iran
  + The US and Russia have a common interest with regards to Iranian nuclear capability
  + While we cannot currently act on those interests, we will need to do so in the future to discourage Iran from pursuing nuclear weapons
** The China Challenge
+ Bruce Jones: China is also seeking to change the world order to its benefit, but in a very different way than Russia. Where do nuclear weapons fit into Chinese thinking?
+ Frank Rose:
  + China presents a fundamentally different nuclear challenge
  + Russia has been very belligerent with its nuclear policy
  + China continues to maintain a no-first-use policy
  + Restrained nuclear rhetoric
  + Aren't trying to match US or Russian arsenals
  + China's primary priority is to maintain a survivable second-strike capability
  + To this end, they see US missile defense initiatives as an existential threat to their nuclear deterrent capability
  + The main concern with China is their offensive anti-satellite and cyberwarfare capabilities
  + We have a (fraying) dialogue with Russia on cyber and ASAT
  + We need to start a similar dialogue with China
+ Michael O'Hanlon
  + It's a mistake to treat Russia and China similarly when it comes to nuclear policy
  + Russia is far more reckless than China -- Russia knows that its power is on the wane, long term
  + China, on the other hand, is more confident -- it knows that its conventional capabilities are on the rise
  + We should be more grateful that China hasn't been more belligerent with their nuclear policy
+ Strobe Talbott
  + China has been a beneficiary of globalization
  + They see it in their best interest to maintain a peaceful world order
+ Michael O'Hanlon
  + Russia is much more willing to overturn international norms
  + China wants to be seen as an equal, but it is willing to work within existing institutions and structures
+ Bruce Jones:
  + China and Russia are playing complementary strategies
  + While China may not condone what Russia is doing, it benefits from Russia's disruptiveness
    + Distracts the US
    + Weakens Europe
  + Main risk for China is that Russia will go too far and will cause a breakdown in the world order which will harm China
** Technology and nuclear weapons
+ Bruce Jones: What impact does cyberwarfare have on nuclear strategy?
+ Frank Rose
  + Cyberwarfare fundamentally changes the nuclear threat landscape
  + We need to keep the potential for cyber-attack as we modernize our nuclear command and control systems
  + Strategic capabilities (nuclear, cyberwarfare, artificial intelligence, missile defense, space-borne weapons) are increasingly becoming integrated
  + One of the mistakes that the Obama administration was that it eliminated the position of Undersecretary of Defense for global strategic affairs
  + Russia and China most definitely do not consider nuclear, cyber and space as separate -- why should we?
  + Unlikely that future conflict will be limited to a single domain
+ Bruce Jones: Could cyber operations be met with a nuclear response?
+ Frank Rose
  + No, there is no cyber-attack which would merit a nuclear response
  + More generally, we need to be more careful about threatening a nuclear response
  + Given that we're not going to use nuclear weapons to respond to a cyber-attack, we need to formulate credible cyber and conventional responses which can be used to meet a cyber-attack
+ Michael O'Hanlon
  + If a cyber-attack, biological weapon or artificial intelligence caused as much damage as a nuclear strike, then we should be open to using nuclear weapons in response
  + Taking nuclear weapons off the table prematurely ties our hands
+ Madelyn Creedon
  + We need to maintain some level of ambiguity in our response
  + In the near term, however, the main danger is theft of intellectual property
  + Even the most severe cyber-attacks perpetrated by Russia have been relatively minor things
+ Strobe Talbot: We can't count on cyber-attacks remaining mild
+ Madelyn Creedon
  + Need to better protect military and critical assets against cyberattack
  + Maintain flexibility in response (be it conventional, cyber, or nuclear)
  + Response should depend on the consequences of the attack, not the nature of the attack
  + Cyberwarfare is part of a strategic whole
  + Need to figure out how we can achieve strategic stability in a world with advanced cyberwarfare capabilities and artificial intelligence
+ Frank Rose
  + Need to improve our ability to adopt and adapt new technology
  + Plans need to be flexible so that our modernization programs can pick up new technologies as they become available
+ Bruce Jones: Should we worry about a medium or longer term future where nuclear launches are automated?
+ Frank Rose:
  + China, Russia and other authoritarian countries don't have the same qualms about AI that we do
  + Need to come up with guidelines about launch automation that everyone agrees to stick to for the collective good
  + It will be difficult to get a formal treaty restricting AI in nuclear weapons so long as nations think the technology can be used for strategic advantage
* Non-Proliferation
** Crisis In North Korea
+ Bruce Jones: Let's talk about North Korea and Iran; what is the state of North Korea's nuclear program, and where is it headed?
+ Jung Pak
  + Kim Jong Un has broken his silence after six years of no negotiations
  + Some of the steps he's taken seem more significant than they are because of how intransigent North Korea was in the seven years prior
  + Kim Jong Un is continuing with his father's policy of offering small cosmetic steps as a sign of good faith, when in fact those steps are neither verifiable nor irreversible
  + Given the centrality of nuclear weapons in the North Korean government's legitimacy, it seems unlikely that Kim Jong Un would give them up for an end-of-hostilities declaration
  + However, we need to keep pressing the North Koreans to see how far they're willing to go under the Singapore Declaration
+ Robert Einhorn
  + Rapid and complete denuclearization was never in the cards
  + However, it is plausible that North Korea will accept limitations or reductions in its nuclear and missile capabilities in exchange for security assurances and economic benefits
  + The joint statement of June 12, 2018 lays out 3 main goals:
    + Improvement of US-North Korea relations
    + Progress towards peace on the Korean Peninsula
    + Progress towards complete denuclearization
  + Trump administration wants concrete benefits before making concessions in any of these areas
  + However, we don't have the leverage to compel North Korea to accept our demands
  + What will the administration do when it realizes that complete denuclearization is off the table?
    + Accept a deal that limits but does not eliminate Nort Korea's nuclear missiles?
    + Long term strategy of pressure, deterrence and containment
    + /So, in other words, the only option is to "stay the course"/
+ Madelyn Creedon
  + Kim Jong Un really wants a peace declaration
  + A peace declaration would be a second trophy, to add to the one for completing North Korea's nuclear weapons program
  + A peace declaration without denuclearization beforehand would allow North Korea to be a nuclear power permanently
+ Jung Pak
  + South Korea has a deep interest in a peace declaration
  + Will the Moon Jae-in administration and more left-wing elements of the South Korean public see the US as holding back reunification?
  + North Korea has an interest in driving a wedge between South Korea and the United States
+ Bruce Jones: Is there any shift in China's attitude towards North Korea?
+ Jung Pak
  + The Chinese administration had been frustrated with North Korea because Kim Jong Un had kept them at arms length while acting provocatively
  + However, lately relations have warmed -- Kim Jong Un has visited China 4 times in 2018 alone
  + Kim is balancing China against the United States
** Iran and the Middle East
+ Bruce Jones: Where does Trump's walk-away from the JCPOA leave Iran's nuclear program?
+ Suzanne Maloney
  + Iran is continuing to abide by the terms of the deal, even though it is paying a significant economic penalty
  + Iran's patience is predicated on a hope for change in the American domestic political situation that allows it to return to the deal
  + However, it's unlikely that Iran can hold out until 2020
    + Massive decline in the value of Iran's currency
    + Consumer products shortages
    + Political uncertainty
  + There is mounting economic and political turmoil in Iran
    + Upcoming replacement of the Supreme Leader
    + Coming of age of post-revolutionary baby boom
  + The real question is whether the Iranian goverment will take President Trump up on his offer to open new negotiations
    + Trump wants a "bigger, better" deal
    + Not clear that the rest of his administration shares that objective or thinks it's realistic
    + Lot of support in in the administration for regime change
  + Iran is caught between a rock and a hard place
    + Negotiate with a partner that has proven unreliable in the past or
    + Try to muddle through and wait out the American political calendar while hoping to forestall mounting internal economic and political pressure
+ Robert Einhorn
  + Common thread in North Korea and Iran strategies: wildly unrealistic objectives and expectations
  + Tremendous pressure on Iran's economy
  + However, it's unlikely that renewed sanctions will be as bad as 2012 and 2013 rounds
  + The not-so-hidden agenda is that the goal isn't to negotiate, the goal is to destabilize the regime
  + Therefore it is unlikely that the Iranians will take up Trump's offer to negotiate
+ Bruce Jones: If Iran continues on its current path, how likely is further proliferation in the region, specifically for Saudi Arabia and the UAE?
+ Suzanne Maloney: 
