#+TITLE: Russia In Revolution: An Empire In Crisis 1890 - 1928 
#+OPTIONS: num:nil

* Introduction
+ Book covers the main events, personalities and developments in the former Russian empire from the late 19th century through the forced collectivization of 1928-29
+ Attempts to answer the "big questions" about the Russian Revolution
  + Why did the tsarist autocracy fail?
  + Why did attempts to establish a parliamentary democracy also fail?
  + How was a small, extreme socialist party able to gain power and hold power through a ferocious civil war?
  + How did Stalin rise to power?
  + Why did he unleash forced industrialization and collectivization on his people?
+ The book is largely concerned with _power_
  + How a determination to hold on to power can cause the old regime to fail to adapt to new developments
  + How those seeking to build a better society can become corrupted
+ Why another book on the Russian revolution?
  + Since the fall of the Soviet Union, a wealth of new scholarly material has come to light
  + Books seeks to give the reader an updated understanding on the events of the Russian Revolution using this new material
  + May more attention than was possible prior to 1991 to issues such as:
    + The imperial and national dimensions of the Revolution
    + Complexity of forces in the civil war
    + Attempts by moderate socialist and anarchist parties to resist the Bolsheviks
    + Peasant and worker resistance to the Bolsheviks
    + Economic privation and suffering of the new regime
    + Economic and social contradictions of the Soviet Union under the New Economic Plan of the 1920s
+ The timeframe of the book is due to the emphasis of some important continuities across the revolutionary divide of 1917
+ The causes of the revolution are categorized into external pressures and internal pressures
  + External pressures - geopolitics and rivalries within the international state system
  + Internal pressures - pressures caused by the undermining of social hierarchies by rapid economic modernization
+ In addition, this book focuses less on the writings of the revolutionaries themselves, and more on the conditions that allowed revolution to be possible
+ The book also focuses heavily on World War 1, since the socialist revolutions of the 20th century were made possible by the social crisis caused by war, specifically
+ The book also focuses on the experience of Eurasian Russia in the Revolution
  + One thing that most histories of the Russian Revolution gloss over is that during the Revolution and the Civil War, the Russian Empire shattered, and had to be reassembled by the Communists
  + Recent research has brought out how the Revolution was shaped by local ecological socioeconomic and ethnic structures
+ Revolutions are different from coups in that the breakdown of the state is total, and this opens up space for mass mobilization
  + The peasantry is excluded from all too many books about the revolution, but they were its primary agents and victims
  + Peasantry rose up against the old rural order, but found themselves bearing the main cost of economic modernization
+ This book also seeks to incorporate new findings from cultural history
  + Bolsheviks were the first to attempt to create an atheistic society
  + However, in order to consolidate their rule, they had to compromise with and appropriate beliefs that they had once excoriated
+ The lack of strong revolutionary impulses in the world today has affected how historians write about the Russian revolution
  + See Russian revolution as the initiator of a cycle of violence that culminated in Stalinism than a flawed attempt to create a better world
  + Russian revolution today is viewed as a historical cul-de-sac - Russia went from capitalism to communism and then back to capitalism
  + From the perspective of Vladimir Putin's Russia, it seems like the hardly anything has changed in Russian political cultures
+ So why should we study the Russian revolution
  + Offered by far the most radical challenge to the existing social order until that time
  + First serious challenge to capitalism
  + The current Russian government is a product of the Revolution and the Cold War that followed, so we need to understand the Revolution in order to understand the mindset of the current Russian government
  + We can learn lessons from how the ideals of the Revolution were corrupted by thirst for power, enthusiasm for violence and contempt for law


* Chapter 1: Roots of the Revolution: 1880s - 1905
+ Collapse of the tsarist regime was rooted in economic and social modernization
+ Pressures were greatly exacerbated by World War 1
+ As society modernized new social classes were created (industrial workers, commercial capitalists) that did not fit into the feudal system of estates
+ The pressures of this modernization, combined with military defeat against Japan, led to the 1905 revolution
+ The 1905 revolution was composed of the middle classes, a militant labor movement and a peasant revolt against the landed gentry
+ Forced Tsar Nicholas II to promise significant concessions and create a constitutional monarchy - October Manifesto
+ However, after the revolution had been suppressed, the Tsar reneged on his promises
+ The years after the Revolution, from 1907 to 1914, were called the "years of reaction", and were largely characterized by a stalemate between the new legislature (the Duma) and the tsarist government
  + In addition, the regime came under fire from conservative groups like the landed gentry and the church for the concessions that it did give
  + Even though there was political stalemate, there was reason to hope that revolution could be averted thanks to economic growth and military modernization
+ However, the outbreak of World War 1 put pressures on Russian society that it was not prepared to tolerate
  + The demands of total war strained the agricultural and industrial economies
  + Increased gap between the common people and the privileged classes
  + Combination of elite dissatisfaction with the management of the war combined with common people's dissatisfaction and economic privation and food shortages would lead to 1917 revolution that would overthrow the Romanov dynasty
+ Russia's development can be characterized as the colonization of a "boundless and inhospitable plain"
  + Russia lacks natural frontiers, which makes it vulnerable to invasion
  + Each invasion (Poles, Swedes, Napoleon, etc.) was repelled, but at increasing human and material cost
  + This led to the creation of an increasingly autocratic and imperial state
+ The state managed to rule its territory for large parts of its history by co-opting non-Russian local elites
+ However, economic development and imperialist ambitions on the parts of other European powers in the latter half of the 19th century put enormous strain on Russia's borders, leading to increasing centralization
+ While Britain, Germany, France, Austria-Hugary, Russia and the Ottoman Empire sought to maintain the fiction of "balance of power" through treaties and alliances, it became increasingly clear that the great powers were unequal in strength
+ As a result, great power relations in the years prior to 1914 were inherently risky, as each power sought to judge how strong the others actually were, and how likely each was to back up its resolutions with force
+ While Russia enjoyed international preeminence after the defeat of Napoleon, that aura of invincibility was shattered by its poor performance during the Crimean War (1853-1856)
  + Result: Russia was denied the right to a navy or to build fortifications on the Black Sea
+ As a result, tsar Alexander II launched a program of far-reaching economic and military reforms
  + Abolition of serfdom (1861)
  + Establishment of conscription and cadet (junker) schools
  + Judicial reforms - limited trial by jury (_How were trials carried out prior to this?_)
  + Establishment of local government institutions (_zemstvos_) and municipal dumas
+ If these reforms had been allowed to proceed, it is possible that revolution could have been averted
+ However, in 1881, Alexander II was assassinated by a member of the terrorist People's Will organization, and many of his reforms were reversed under his son, Alexander III
+ The reforms of Alexander II did little to bolster Russia's international influence
  + Russia's gains in the war of Russo-Turkish War of 1877-1878 were much reduced by the politicking of Otto Von Bismarck at the Congress of Berlin
  + Bismarck's actions underscored the threat posed to Russia by a unified and powerful Germany
  + This eventually led to the formation of an alliance with France, and France would remain allied with Russia against Germany until 1917
+ Although Russia was worried about the threat posed by Germany, it was actually attacked by Japan
+ Russo-Japanese War of 1904
  + Russia and Japan were rivals in Manchuria
  + Russia had recently inagurated the Trans-Siberian railway, which was designed to open up the Russian hinterlands to settlement
  + Russia pressured the Qing dynasty of China to allow it to build the China Eastern Railway as a spur line to connect the Russian base at Port Arthur with the Trans-Siberian Railway
  + This was viewed as a provocative move by the Japanese, who launched a surprise attack on the Russian fleet anchored at Port Arthur
  + Russia then sent its western fleet on a long (18,000 mile) voyage which ended with defeat at the battle of Tsushima
  + The defeat of two Russian fleets by an Asiatic power was humiliating and served to harden domestic political opposition to the tsar
+ The Russian empire was a vast conglomeration of different ethnicities and religions
  + Excluding Ukrainians, ethnic Russians were actually a minority (44%) of the empire
  + People were defined in terms of social estate and religion
  + There was also a distinction between Slavs and "inorodsty" ("person of other origin" - a term applied to non-Slavs living in Russia)
+ Historically, the empire had been managed by allowing local elites to rule the borderlands
  + Significant degree of religious tolerance, especially with regards to Islam
  + Many different local legal and judicial systems
+ However, as security concerns mounted, this diversity was increasingly seen as a problem
  + In the late 1800s there were increasing efforts to impose Russian as a standard language across the Empire
  + Especially hard crackdowns against Poles and Jews
  + Central Asia was ruled in an increasingly colonial manner with Russian overlords exerting more and more control over the "less civilized" peoples
  + That said, the Russian empire was still formally multi-ethnic, defining itself as "rossiskaia" (state containing all the peoples of the Russian lands) as opposed to "russkaia" (land of the Russian people)

** Autocracy and Orthodoxy
+ Tsar Nicholas II came to power in 1894 (after the death of Alexander III)
+ Nicholas thought of himself as a monarch governing my divine right
+ Even the Basic Law of 1906, ostensibly created to ensure a constitutional monarchy said that Nicholas II was an "autocratic and unrestricted monarch"
+ Nicholas II was also hostile to his own bureaucracy and sought the advice of holy men like Rasputin
+ Even though the Russian state had sweeping powers on paper, in practice it was quite weak
  + Narrow tax base
  + Limited material and human resources
  + Understaffed administration
  + Corruption
  + Inefficiency
+ These drawbacks had been noted by tsar Alexander II, who had sought to address them with reforms
+ However, these reforms were largely shelved after Alexander II's death
+ Nicholas II's two most talented advisors, Sergie Witte (Finance) and Peter Stolypin (Interior) both recognized that reform was necessary
+ Although many have likened pre-revolutionary Imperial Russia to a police state, this overstates the central authority of the state
  + The police did have wide ranging powers to arrest people for subversive activity
  + The Okhrana, the secret police, had agents in factories, institutions and revolutionary parties
  + However, there were not nearly enough police to turn these theoretical powers into an actual police state
  + A single constable, assisted by a few low-ranking officers, might find himself responsible for 4,700 sq. km. and anywhere between 50 and 100 thousand people
  + Wide powers were delegated to provincial governors by a central state that didn't have the bureaucratic capacity to execute its formal powers
  + Rather than building up an effective police force, the state turned to the army to quell uprisings as the developed
+ In practice, many parts of Imperial Russia effectively governed themselves, with little oversight from the central state
  + The new zemstvo institutions were supposed to maintain order after the emancipation of the serfs, but the central state did little to ensure that they were exercising leadership in a way approved by the government
  + At the township level, assemblies of heads of household, known as _skhod_ were responsible for ensuring that local infrastructure was maintained and taxes were paid
  + Tsar Alexander III established the office of the _land captain_, an appointed representative of the autocracy
    + Oversaw the activities of the village and township assemblies
    + Had the authority to act as judge in certain civil and lesser criminal cases
    + Was widely reviled because the office of land captain displaced roles that had earlier been held by elected representatives of the villagers
+ Another pillar of social order was the Orthodox Church
  + Administered by the Holy Synod which had been subsumed into the imperial bureaucracy by Peter The Great
  + Led by Procurator Konstantin Pobedonotsev, an extreme reactionary, from 1880 to 1905
  + The Church held 3 million hectares of land and 1/3 primary schools in the empire
  + Over 40 thousand churches 50 thousand priests, 21 thousand monks and 70 thouand nuns
  + Although the Orthodox Church was the official state religion, there were substantial religious minorities in the Empire
    + Muslim minorities in Central Asia
    + Roman Catholics in Poland and Lithuania
    + Jews in the Western Provinces
  + While the church was never completely monolithic or unchanging the increasing secularism of the intelligentsia and the transition from a rural to an urban economy put great strains upon the church in the years before the revolution

** Popular Religion
+ Like all things in Russia, there was significant divergence between official religion and religion as it was actually practiced
+ Peasant religion was much more oriented towards warding off various demonic forces from the Devil, and also from various other spirits of woods and streams
+ Villages often had their own unofficial saints and icons above and beyond those officially recognized by the Church
+ While these unofficial icons and saints were occasionally labeled heresies, they were increasingly tolerated after 1905
+ Although popular religion was strongly traditionalist, it was not completely unchanging in the face of new technologies and social norms
  + Trains allowed many more people to make pilgrimages
  + Increasing literacy allowed people to read popular stories about saints and stories of miracles and healing
  + Cheap printing allowed the distribution of icons
  + Migration and schooling allowed a more individualized faith; not necessarily secularization
+ Popular religion also had a strong train of apocalyptic thought, due in part to the political and social upheavals that Russia was experiencing at this time

** Agriculture and Peasantry
+ Russia, at the turn of the 20th century, was an overwhelmingly agrarian society
+ Rural peasantry had a precarious existence
  + Population growth meant that more people had to farm the same amount of land
  + Extremely high child mortality - in 1905 fewer than half of children born reached the age of 5
  + A single harsh winter combined with a bad harvest could lead to widespread famine
  + Diseases such as measles and diptheria were endemic
+ As a result, village society was extremely conservative, in order to ensure the survival of the community
  + Villages were organized as communes with common ownership of land
  + Land was periodically redistributed among the villagers by a council consisting of all the village heads of household
  + In addition, this council decided planting and harvesting schedules and decided who would grow which crop
  + The council also acted as an interface with the larger bureaucracy of the state, making sure that taxes were paid and law and order were maintained
+ Village society was patriarchical, however, women could gain substantial informal power by dint of their household responsibilities and their primary role in arranging marriages
+ Another burden on the peasantry was the redemption payments that they owed the nobility in exchange for their freedom - renumeration payments were imposed by Alexander II when he eliminated serfdom
  + _bullshit, IMHO - it's not freedom if you have to pay for it_
+ Despite these burdens, however, there were indications that the quality of peasant life was improving around 1900
  + Healthy deposits in rural savings banks
  + Increases in agricultural yields that outstripped population growth
  + Increasing health of army conscripts
  + Increased productivity of commercial agriculture
+ Although life overall was (probably) improving for the peasantry, these gains were very unequally distributed, and indicators for e.g. the central black earth, and Volga provinces were in decline
+ The biggest change in pre-Revolution Russian agriculture were the reforms imposed by Peter Stolypin after the 1905 unrest
  + Allowed families to buy out their share of communal property and farm it as they pleased
  + Intended to create a class of conservative yeoman farmers who would be a base of support for the tsarist regime
  + _So does this mean that the kulaks were actually intended to be reactionary counterrevolutionaries?_
  + By 1914 15.9% of land had been privatized, at which point the strain of the war put an end to further domestic reforms
+ As capitalism took hold in the countryside, there was increasing social stratification among the peasantry
  + The richest peasants (usually with privatized land) were known as _kulaks_ (fists)
  + Unclear how much socioeconomic mobility there was - some have argued that intergenerational socioeconomic mobility was high, since wealthy families would have lots of children who would subdivide and redistribute the wealth
  + Also unclear how to measure socioeconomic class, since land ownership was only one of many possible ways to be wealthy
+ If peasant life was improving, why was there so much unrest?
  + Peasants thought they'd been cheated in the process of abolishing serfdom
  + Nobles were owed 49 years of redemption payments
  + Actual amount of land the peasants received was less and of lower quality than the land they had farmed as serfs
  + Absentee landlords were an affront to the peasant ethic that only those who lived on and worked the land should own it
  + _I'm not going to lie - the peasantry was cheated by the abolition of serfdom_
+ Although nobles were compensated for the loss of their serfs, their fortunes still entered a steep decline around the turn of the century
  + While there were some nobles with large estates, a large number had farms smaller than 150 hectares
  + Moreover, the gentry was just as ill-equipped as the peasantry for the transition to capital-intensive commercial farming - nobles and peasants alike encountered the same issues getting financing
+ The tsarist state, needing educated soliders and industrial workers invested in teaching rural children how to read and write
  + Literacy increased to 21.1% by 1897, with 13.1% of women able to read and write as compared to 29.3% of men
  + Urban literacy significantly outpaced rural literacy, with 45% of urban dwellers able to read and write
  + Though literacy increased steadily in the years leading up to 1914, even in 1914 less then 20% of school-age children were actually enrolled in school
    + Many families felt that only the firstborn son needed functional literacy - education was strictly optional for the other children
  + While the state acknowledged the need for education, it also recognized that education could lead to free thinking and rebellion against the state
  + As a result, it closely monitored primary education to ensure that state propaganda was also being transmitted in addition to the knowledge of how to read and write

** Industrial capitalism
+ Ivan Vyshnegradskii, finance minister from 1887-1892 started a program to increase Russia's industrial output to counter a perception of relative decline
+ This program was greatly expanded upon by his successor Sergei Witte (finance minister from 1892 to 1903)
+ Witte hit upon the building of railroads as a way to stimulate economic growth
  + Increased amount of track from 30,600 to 56,500 km
  + Completed the Trans-Siberian railroad
  + While increased trackage didn't immediately lead to increased trade, it did stimulate the coal and steel industries of the Donbass
+ Russia adopts the gold standard in 1897 in order to make itself more attractive to foreign investment
+ The alliance with France leads to increased French investment in mining, metallurgy and engineering
+ British investment was significant to the development of the Baku oil region and gold mining
+ While Germany was seen as a strategic threat to Russia, German investment was significant as well
+ State-backed industrialization was financed mainly by the sale of grain
+ While the state was significant in Russia's industrialization, Russia also had a robust private sector focused mainly on consumer goods, textiles, and foodstuffs
+ Although Russia was in the top 5 of overall industrial producers (behind the USA, Germany, Britain and France), it's production per-capita was much less than its peers
+ Industrialization led to urbanization (though, at a slower pace than in other countries)
  + By 1913 St. Petersburg has 2.2 million residents, Moscow has 1.6 million residents, and there are over a hundred towns with over 50,000 people and over 20 with 100,000
  + Much of the move to the cities was seasonal, with peasants moving to the city to work in the off-seasons and returning to the villages for harvests
  + Urbanization put a severe strain on local governments and infrastructure
    + St. Petersburg was "the most unsanitary capital in Europe"
    + Cholera epidemics
    + In 1920, fewer than half of homes had water and sewage
  + The lack of infrastructure was due to the lack of tax revenue for local municipal governments, combined with corruption and incompetence
  + Moscow was an exception to the trend of overburdened civic infrastructure and incompetent local government
    + "Reasonable" water and sewage
    + Electric street lights
    + Trams
    + Free health clinics
+ The attitude of industrialists to the autocracy depended on their region and industrial sector
  + Textile manufacturers of the Moscow region were socially conservative, but their lack of dependence on state orders meant that they could and did advocate for political reform
  + Textile manufacturers in Poland (around Łódź) were primarily German, and were more supportive of the autocracy
  + St. Petersburg was home to mostly metal and engineering works - these industrialists were more concerned with preserving their influence over the government which gave them their orders than in reform
  + The iron and steel works of the Donetsk region were "paternalistic at best, iron-fisted at worst" and very supportive of the autocracy
+ Government industrial policy
  + Generally hand-off
    + Low taxes
    + No income tax introduced until 1916
  + However, there were many within the Interior Department, especially, who saw something unseemly and exploitative about making money from industry rather than agriculture
  + That said, the government always took the side of employers in labor disputes, so in practice, the power of employers was near-absolute
+ Working conditions
  + Universally terrible
  + Workers worked 11 or 12 hour days
  + Accidents were common and compensation for accidents was miserly
  + Strikes and trade unions were illegal
+ Industrialization and urbanization upset the system of social estates which had been used by the government to regulate society
  + Social estates
    + Nobility
    + Clergy
    + Merchants
    + Townspeople
    + Peasants
  + Social estate status determined which educational and commercial opportunities were available to you
    + _Like a caste system?_
  + While Alexander II had sought to end the system of social estates, his assassination led successor governments to try to strengthen it
