#+TITLE: Trust Me I'm Lying: Confessions of a Media Manipulator (outline)
#+OPTIONS: num:nil toc:nil

* Book Details
+ Title: Trust Me I'm Lying: Confessions of A Media Manipulator
+ Author: Ryan Holiday
+ Publisher: Portfolio, Penguin
+ Copyright: 2013


* Introduction
+ Ryan is a media manipulator
+ Lies to the media so they can lie to you
+ Case study: Tucker Max movie _I Hope They Serve Beer In Hell_
  + Deliberately provokes controversy
  + Buys billboards and defaces them himself
  + Deliberately calls and provokes feminist protestors to get free controversy
  + Took a small spark of controversy and fanned it into a conflagration of publicity
  + Successful viral media campaign for an otherwise unremarkable book/movie
+ Full-time job: director of marketing for American Apparel
+ Also does publicity for others on a contract basis
+ Eventually Ryan gets sick of the hustle and decides to write this book
  + Also worries about the impact his industry is having
  + Things that start out as jokes or publicity pieces are having negative consequences long after the campaign ends
  + Internet doesn't forget
  + Sees a proliferation of "journalism" that carries the same hallmarks of manipulation that he specializes in
+ Book is a catalog of case studies in media manipulation
+ Goal is to show that vulnerabilities exist
+ Needn't worry about empowering the "bad guys" - they're already exploiting these vulnerabilities

* Chapter 1: Blogs Make The News
+ Politico's coverage of Tim Pawlenty
  + Tim Pawlenty is an obscure governor from an obscure state
  + Hasn't even officially declared his candidacy for the 2012 election
  + Yet there's a reporter from Politico following him around
  + Why is Politico covering Tim Pawlenty when other, more well-resourced publications are dismissing him as not-notable?
  + Tim Pawlenty eventually becomes a candidate and then his candidacy eventually goes bust
  + In the process, he generates millions of pageviews and ad impressions
+ Blogs matter
  + "Blog" - any online publication whether it considers itself a blog or not
  + All blogs are subject to the same incentives and fight for readers with the same tactics
  + However not all blogs are equal
    + Some blogs are far more influential than others
    + Influence stems from type of audience rather than total audience size
    + A blog that's widely read by the media elite punches far above its (audience size) weight
  + Blogs influence what gets printed in the news
  + Blogs influence what gets spread via word-of-mouth and social media
    + Blogs give rise to the memes that become "common knowledge"
    + Blogs tell us which budding stars to turn into true celebrities
  + If one can figure out how to manipulate the rules that govern blogs, one gains a massive influence over culture as a whole
+ So why did Politico cover Tim Pawlenty?
  + Blogs need to generate far more content than either cable news or newspapers
  + Newspaper has to fill a broadsheet newspaper once a day
  + Cable news has to provide 24 hours of programming per day
  + A blog has a near infinite amount of space and an audience that's always looking for novelty
  + Has to be constantly generating content in order to keep fresh content at the top
  + The site that covers the most stuff wins
  + In a sense, Politico had no choice but to cover Tim Pawlenty - if they didn't cover him, they would have lost the story to someone else
  + Blogs need traffic to sell, and need to produce fresh content constantly in order to attract that traffic
  + Political blogs get a huge spike during elections
  + Problem: elections only happen once every four years
  + Solution: broaden and lengthen election cycle to increase traffic in off-years
    + Broaden: cover more candidates
    + Lengthen: start covering candidates earlier and earlier
  + This process reaches its logical conclusion with Tim Pawlenty
    + Coverage begins well before campaign kick-off
    + Coverage is of a candidate who has no realistic hope of winning the nomination
  + Arguably, coverage of Pawlenty as a "potential candidate" and "real contender" helped turn him into a "real" candidate
  + Even though he didn't win the nomination, media coverage of Pawlenty was enough to make Mitt Romney seek his endorsement - blogs had real world impact, even though Pawlenty did not become the Republican candidate for President
  + Blogs need traffic, so they'll do whatever they can to drive traffic to themselves
  + Blogs prioritize traffic over truth
    + Rush to report first
    + Report poorly sourced scandals

* Chapter 2: How To Turn Nothing Into Something In 3 Way-Too-Easy Steps
+ "Trading up the chain"
  + Post story on small blogs with low newsworthiness standards
  + Get that story picked up by larger and larger outlets
  + Eventually get mainstream media coverage
+ Example:
  + Nonprofit posts story on Brooklyn blog that's a known source for Huffington Post
  + Huffington Post picks up on it, posts story in New York and LA editions
  + Huffington Post article is entry-point for local CBS affiliate
  + CBS affiliate decides story is newsworthy and posts a short article with a video
  + CBS link is fodder for Reddit and other aggregators
  + Results in a massive influx of donations
  + Nonprofit is funded for two years from this one story
+ How was this accomplished with no marketing budget?
  + Content filters up as much as it filters down
  + Small blogs often act as "farm teams" for larger organizations
+ The lay of the land
  + Small blogs must write several times a day to generate revenue
  + These blogs are constantly scanning social media and other sources for "news"
  + These stories, if they're catchy, are picked up by larger blogs like Gawker and Huffington Post
  + Finally mass media pulls stories from these larger blogs and link aggregators (Reddit, Digg, etc) and adds them to the "national conversation"
+ This chain simplifies to three broad levels
  + Level 1: Entry point
    + Small blogs and hyper-local news sites
    + Usually write about a geographically or subjectively narrow topic, but can be induced to run a story if it'll bring in pageviews
  + Level 2: Legacy Media
    + Mix of online and offline sources
    + Local news
    + Online sources that are subsidiaries of larger brands (i.e. SmartMoney and CNN, Monkey Cage Blog and Washington Post)
    + Critical in helping a story go viral - multiple mentions in these types of sources creates "chatter"
  + Level 3: National
    + Large, nationally recognized publications (i.e. New York Times, CNN, etc.)
    + Getting a story here requires less pushing and more massaging
    + Which Level 3 source you get depends largely on which Level 2 sources you target
      + Observe which Level 2 sources the national news outlet you're targeting draws from and try to get your story into those
    + Level 1 and Level 2 sources will help when trying to get your story into Level 3 - Level 3 coverage means more pageviews and revenue for them
    + Create the perception that the meme already exists and all thexsy're doing is popularizing and documenting it
+ Levels 1, 2, and 3: How I traded up the chain
  + Campaign for Tucker Max movie
  + Start by deliberately vandalizing billboards
  + 2 local sites targeted
    + MediaBistro Fishbowl LA
    + Curbed LA
  + Call SJWs with anonymous tips to create protests - generate controversy where it wouldn't otherwise have existed
  + Protests are telegenic - local news team sends cameras and reporters
  + Use local news coverage and MediaBistro/Curbed coverage to land stories in Gawker - Gawker is a known source for Washington Post
  + Gawker coverage and local news video results in Washington Post covering Tucker Max
  + Washington Post coverage gets publicity team access to talk shows and late-night TV
+ The media: dancing with itself
  + Reporters at all levels are under enormous pressure to produce stories, non-stop
  + "Seller's market" for "news" and controversy
  + Even jokes and sarcastic remarks can be treated as true quotes and blow up into rumors
    + Kurt Warner jokes that Brett Favre (who was then embroiled in a sexual harassment scandal) should be the next guest on "Dancing With The Stars"
    + This joke is picked up by a sports blogger
    + The sports blog article is then picked up by an Iowa news outlet, which doesn't understand that the story is covering a joke
    + From the Iowa local news outlet, the story then lands in USA Today
    + At this point Dancing With The Stars has to go on record saying they wanted nothing to do with Brett Favre
+ A true fool feeding the monster
  + Another example of non-stories blowing up (and leading to loss of life) is the Terry Jones Koran burning incident
  + Terry Jones runs a small church in Florida (/where else?/)
  + Announced plans to burn a Koran
  + Story initially picked up by a small blog called the /Religion News Service/
  + Trades up to Yahoo
  + CNN pulls from Yahoo and makes the Koran burning a national story
  + CNN and mentions on other national news outlets cause President Obama to get involved, urging Jones to not burn the Koran
  + Obama's involvement turns the story into an international story
  + Terry Jones, after some hesitation, goes ahead and burns the Koran
  + Koran burning leads to riots in Afghanistan, leading to 30 deaths
  + The real question isn't whether Jones should have burned the Koran or not, instead it's, "Why should we care?"
    + Why was a pastor of a no-name church in Florida able to get the attention of the President of the United States?
+ /Exercise for the reader:/
  + /Take a national media outlet (e.g. New York Times, Washington Post, LA Times, USA Today, etc) and find the blogs it pulls from/
  + /Take one of those blogs and see where it gets its stories from/

* Chapter 3: The Blog Con: How Publishers Make Money Online
+ Traffic is money
  + Blogs make their revenue from selling ads
  + Revenue = CPM (cost per thousand impressions) \* pageviews
  + Ad buyers buy a certain number of impressions for their ad
  + Ad networks allocate that pot of money to blogs based upon readership and demographic information
  + More traffic = more money now, and more ad spend later (since the blog becomes a reliable source of impressions)
  + Ads don't distinguish by type of story - all that matters is that the ad is displayed and the viewer has a chance to see it
  + Fake news, real news, whatever gets the ad to load "wins"
  + Blogs don't have much control over CPM, so they try to maximize pageviews
+ Scoops are traffic
  + TMZ turned the art of getting scoops into a science
    + Mel Gibson's anti-semitic rant
    + Rhianna/Chris Brown
    + Michael Jackson's death
  + Scoops and exclusives allowed TMZ to go from a no-name website to a $20 million a year franchise with its own syndicated TV show
  + The price for all of this is publicizing a lot of "scoops" that turned out to be non-stories
  + Scoops are hard to obtain, so a lot of blogs pretend that a story is exclusive to them, knowing the reader won't check other sources to verify that the exclusive is, in fact, exclusive
    + Example: Gawker's coverage of Tom Cruise's involvement with Scientology
    + Story was originally reported by Mark Ebner
    + Gawker reported the story as if it were their own, even though they'd taken it from Mr. Ebner
    + Fake scoops and exclusives aren't as much of a problem in older media - older media are trying to maintain a reputation, whereas blogs are trying to build publicity
+ Using names to build a name
  + Big name bloggers can bring their followers to your site
  + Bloggers like Jason Calcanis, Andrew Sullivan, Megan McArdle, Nate Silver, etc. are big names and switch publications like star athletes switching teams
+ The blog con: names, scoops, and traffic create an exit
  + Blogs are not built to be sustainable businesses
  + Designed to capture traffic and ad revenue, then get sold (usually to an established media outlet)
  + The need to show massive revenue growth in a short period of time makes blogs desperate
  + Every blog is a mini-Ponzi scheme - unsustainable growth leads to overvalued prices and the last buyer is left holding a worthless asset
+ Anything goes in the den of thieves
  + Michael Arrington, owner of TechCrunch, routinely invests in companies that TechCrunch covers and doesn't disclose that conflict of interest in the coverage
    + This is legal because the companies are not-yet-public startups, so insider trading laws don't apply
  + Blogs crave influence even more desperately than traffic; influence makes blogs attractive in a way that raw traffic volume can't
+ Enter the manipulator
  + The fact that blogs aren't sustainable and need to post high traffic and revenue growth makes them exploitable by anyone who has controversy (real or fake)

* Chapter 4: Tactic 1: Bloggers Are Poor: Help Pay Their Bills
+ There are many ways to bribe people other than by handing them a stack of bills
+ Find bloggers' incentives and co-opt them
+ Blogging emphasizes speed over accuracy
+ Bloggers are paid a flat rate, plus a bonus depending upon how many pageviews their articles get
  + Gawker actually had a leaderboard in its office that showed who was getting the most pageviews
  + If you were at the top of the leaderboard, you got a higher share of the revenue
  + If you were at the bottom, you were at risk of getting fired
+ Henry Blodget - a blogger needs to generate 3x their annual salary, benefits, and share of overhead in pageviews each month in order to break even
  + Example: blogger getting paid $60,000 needs to generate about 1.8 million pageviews per month, every month
+ Twitter accounts are even more mercenary than bloggers - many high-follower twitter accounts can be paid to retweet anything
+ The reason that bloggers and social media personalities are paid so little is because what they produce is of little or no value
+ Ripe for exploitation
  + If bloggers want to get rich or even just break even, they have to find other sources of revenue
  + Free stuff
    + American Apparel has two full-time employees whose job is to find up-and-coming fashion bloggers and shower them with free stuff
    + Handing out free tickets or backstage passes does wonders for getting positive coverage for music and movies
      + Blogs may or may not report that they were compensated by the someone affiliated with the product they're reviewing
      + Even if individual blogs report, having a lot of positive reviews can be useful for building "buzz"
  + Help bloggers get a better job
    + The best way for bloggers to make money is to make a name for themselves and then become an established pundit or media personality
    + This warps coverage - bloggers won't write negative stories about people who might hire them in the future
    + The best way you can get gratitude from a blogger is to feed them some juicy stories when they're getting started, and then ask them to promote your stuff once they've made a name for themselves
+ The /real/ conflict of interest
  + The pay-per-pageview model creates a conflict of interest for every topic a blogger might write about
  + Conflict isn't in what they write, but /how/ they write
  + Blogs are constantly pushed to be more controversial, more attention-getting
  + If you want influence with bloggers become a reliable source of controversy

* Chapter 5: Tactic 2: Tell Them What They Want To Hear
+ Journalists rarely see or experience events firsthand
+ They're entirely dependent on self-interested sources
+ Reputable journalists verify sources and identities
+ Bloggers publish unsolicited, unverified information in an attempt to be the first to break a new story
+ The deliberate leak
  + Ryan needed to get some information out fast during a lawsuit
  + Writes up an internal memo, sends it to the all-hands mailing list, then prints it, scans it, and sends it to a blogger
  + Blogger publishes the "leak" with attention-grabbing headlines
  + Gets far more coverage than if the same information had been released as an official statement
  + Took advertising images that couldn't be shared due to copyright concerns and shared them with Gawker - got 90,000 views for free
  + Gawker ended a Congressman's career based upon an anonymous tip from a girl who'd allegedly exchanged texts with him
+ Press release 2.0
  + When Internet journalism started, pundits were heralding the end of the press release
  + Journalists would be free to dig beyond the surface to find news of their own
  + As it turns out, bloggers love press releases
  + Press releases do all the work for you
    + Pre-written material
    + Lays out the "angle" for you
    + Comes from a news wire, so the blogger isn't on the hook if the story turns out to be false
  + Ryan quickly learned to put out press releases for /everything/ to the point of putting out press releases when he launches new colors of already existing product lines
  + Even if press releases aren't published by bloggers, they still have great SEO, so people researching your company will find them
+ Not even needing to be the source
  + The incredible pressure to produce leaves bloggers little time for verifying sources or conducting background research
  + Bloggers are entirely at the mercy of press releases, media kits, official documents and Wikipedia
  + Wikipedia is where bloggers all do their background research, so manipulating the framing of an issue on Wikipedia
  directly affects how bloggers treat the subject down the road
    + If your Wikipedia page says you're a "failed screenwriter", that's the framing that will be used in interviews, regardless of what success you've had in other fields
    + Ryan has told his clients to use specific words or phrases in interviews to get those quotes onto their Wikipedia page, knowing that reporters will blindly copy that text into their own articles
    + Ryan takes advantage of misinterpretations of Wikipedia facts to paint his clients in a more flattering light
      + Tucker Max's book was on the New York Times bestseller list on 3 separate occasions, in 2007, 2008, and 2009
      + Ryan adds this fact to Wikipedia
      + A blogger than misinterprets this data and thinks it means that Tucker Max's book has been on the New York Times bestseller list for three years running
      + Ryan then uses that blog as a source to update Tucker Max's Wikipedia page to say that he's been on New York Times bestseller list for three years running
      + Wikipedia doesn't care about truth, it cares about verifiability
+ Trust me, I'm an expert
  + HARO: Help A Reporter Out
  + Tool that connects reporters with self-interested sources
  + HARO can be exploited to get free publicity on almost any topic
  + Respond to low-level bloggers to get quoted, and then use those quotes to make a name for yourself as a "recognized expert" on whatever you're trying to promote
  + Trade up the chain until you get quoted in the mainstream media
  + Although HARO advertises itself as a research tool, it's really a way for journalists to get quotes to add the appearance of substance to the stories they're already writing
  + Example HARO requests
    + Looking for new and little-known apps to save families money
    + Looking for horror stories relating to mortgages, student loans, credit reports, debt collectors or credit cards
    + Looking for stories about a man who took on new household responsibilities after losing his job
  + These are not journalists looking for experts to teach them about a field they're unfamiliar with, they're journalists who've already written a story and need anecdotes to add the appearance of substance
  + HARO helps journalists create the false impression of balance; look for token quotes so that their stories appear to address both sides of any issue
+ Forgetting my own bullshit
  + Ryan got a quote in the L.A. Times, responding to the question, "What is the classic book of '80s and '90s?"
  + Asked the question under a pseudonym and replied with his real name
  + "Discussion" was picked up by Marginal Revolution (a popular economics focused blog) and got into the L.A. Times from there

* Chapter 6: Tactic 3: Give Them What Spreads, Not What's Good
+ The chief driver of traffic is social media sharing
+ If your story isn't shared, it's not generating revenue
+ A tale of two city slideshows
  + Slideshows, in general, are great revenue drivers for blogs
  + Each slide counts as a new page, so a slideshow can get 10-20x the number of pageviews as an article
  + Slideshows showing abandoned buildings in Detroit are widely shared
  + Slideshows showing foreclosed houses accompanies by their owners are not widely shared
  + Why is one so much more viral than the other?
+ One spreads, the other doesn't
  + [[https://newrepublic.com/article/81954/detroit-economic-disaster-porn][The Case Against Economic Disaster Porn]]
  + Pictures of abandoned Detroit ruins are transcendent; pictures showing the real human cost of the collapse of Detroit are depressing
  + Transcendence and inspiration spreads, depression doesn't
  + The economics of online publishing prevent a true picture of Detroit from being widely disseminated
+ The DNA of the virus
  + [[https://sci-hub.cc/https://doi.org/10.1509/jmr.10.0353][Berger, Milkman (2012): What Makes Content Go Viral]]
    + The most powerful predictor of virality is how much anger an article evokes
    + 1 std dev. increase in the anger rating of an article is equivalent to 3 hours on the front page of the New York Times (in terms of number of shares)
    + Happiness spreads too - 1 standard deviation increase = addl. 1.2 hours on the front page of the New York Times (not as good as anger, but still pretty good)
    + Sadness, on the other hand, seems to suppress sharing
  + Online publishing is designed to find and create high-valence emotional stories
  + The problem is that most information doesn't have high emotional valence
  + Ryan knows this and frames his interactions with bloggers to ensure that they get high-valence material
+ Giving the bastards what they want
  + Ryan deliberately designs American Apparel ads to be as provocative as possible
  + Every re-share of the ad is free publicity and free marketing
  + Created a set of ads showing adult-film star Sasha Grey completely nude
    + Ads appeared on two small blogs
    + Purpose of the ads wasn't to sell clothing (after all, she wasn't wearing any!)
    + Purpose of the ads was to be extremely high-valence emotional content that others would write about
    + Doesn't matter that some blogs wrote about the ads with disgust, while others praised the ads - the goal is to get people writing and talking about the ads in the first place
  + Chatter and controversy correlated with sales spikes, and Ryan was able to use these tactics to grow American Apparel's online sales from 40 million dollars a year to 60 million dollars a year
+ Hidden consequences
  + February 19, 2009: CNBC announcer Rick Santelli has a meltdown on the floor of the Chicago Mercantile Exchange
  + Talks about having a "tea party" to dump mortgage-backed derivatives into Lake Michigan
  + CNBC, instead of treating this as an embarrassing episode to be hushed up, posts the video to the front page of their website
  + Drudge Report picks it up and it goes viral from there
  + "Humiliation should not be suppressed, it should be monetized"
  + While the clip initially spreads as a joke, it finds resonance among some conservatives and they form the Tea Party movement
  + Meanwhile liberals see the clip as a conspiracy to dogwhistle to the Right and energize it in the face of upcoming elections
  + Both sides miss the fact that the point of the clip wasn't to push any particular political sentiment, but to spread controversy for the sake of spreading controversy
  + Once the controversy was going, virtually no one remembered what the initial spark was
+ Viral content fades, but its consequences do not
+ Publishers and marketers have incentives to make content as anger-inducing as possible
+ Online news doesn't necessarily lie by omission, rather it lies by transmission
+ Almost everything is published, but only a few things spread enough for most people to hear about them

* Chapter 7: Tactic 4: Help Them Trick Their Readers
+ The best way to get traffic is to be evasive and misleading
  + Set up a mystery in the headline and explain it after the reader clicks
  + A good question brings twice the response of an emphatic explanation
+ Bloggers justify their misleading question-headlines because they see it as a way to get readers to click on and read "more-fair" stories
+ The problem is that the stories aren't usually more fair than the headlines
+ If you want to manipulate blogs, give them a headline
+ When giving official comments, leave room for bloggers to speculate by deliberately not fully addressing the issue
+ If sending in tips, ask a lot of rhetorical questions
+ For blogs, practical utility is a liability
+ Being, final, authoritative, or useful isn't good for user engagement
+ Getting engaged with content
  + Articles are deliberately inflammatory to get users to leave comments
  + Publishers want users to leave comments because the process of logging in or signing up can yield anywhere between 5-10 additional pageview from that one user
  + The best way to get online coverage is to tee up an article that will get a lot of comments
  + Ryan would deliberately leak horrible things that Tucker Max did as promotion for the Tucker Max movie because he knew that those would get lots of comments
+ You are being played
  + A click is a click and a pageview is a pageview
  + Bloggers don't care how they get those clicks and pageviews
  + The only purpose of the headline is to get you to click through to the story
  + Whether you get anything out of the story is immaterial
  + The purpose of the story is to get you to comment
  + The purpose of online publishing is to string the reader along as long as possible, in order to extract the maximum number of pageviews from that reader

* Chapter 8: Tactic 5: Sell Them Something They Can Sell (Exploit the One-Off Problem)
+ The current condition of online media is analogous to the era of the "yellow press"
+ Overview of media history
  + The Party Press
    + Media in the US starts out as being mouthpieces of political parties
    + Subscription was mandatory with party membership, guaranteeing revenue and readership
    + Primarily opinion, not news
    + Limited in scope and impact
  + The Yellow Press
    + Era begins when Benjamin Day launches the /New York Sun/ in 1833
    + New business model
      + "Cash and carry" - you pay for the newspaper up front, one issue at a time
      + Solved problem of unpaid subscriptions
      + Invented Help Wanted and Classified sections as a way to drive additional revenue
    + Newspapers had to be exciting enough to fight for sales on street corners, taverns and train stations
    + Relied on gossip and breaking news first
      + /Sound familiar?/
    + The /New York Sun's/ success soon inspires competition
      + James Gordon Bennett - /New York Herald/
        + Soon becomes the largest circulation paper in the country
        + Anti-black, anti-immigrant, anti-subtlety
        + Role is "not to inform, but to startle"
      + Joseph Pulitzer - /The World/
        + "Not just cheap, but also bright. Not just bright, but also large"
    + The need to sell issues individually creates the "one-off" problem - each issue has to be individually compelling in a standalone way
    + There aren't enough important events occurring daily to support selling on a one-off basis
    + If there isn't enough news to sell, publishers have to manufacture news
      + [[https://en.wikipedia.org/wiki/Roscoe_Arbuckle][Fatty Arbuckle Scandal]]
    + The need to sell papers meant that papers were okay with being manipulated as long as it meant that they ended up with more sales
      + Paid tipsters and informants large amounts of money for dubious news
    + Papers thrived during the Civil War - war meant that there was lots of important, sensational news
    + Spanish-American War was arguably manufactured by papers that wanted another war to drive sales
      + "You give me the pictures, I'll give you the war"
    + W.J. Campbell identified the following features of yellow journalism
      + Prominent headlines screaming about relatively unimportant news
      + Lavish use of pictures (often of little relevance)
      + Impostors, frauds, faked interviews
      + Color comics and a large Sunday supplement
      + Ostentatious support for underdog issues
      + Overuse of anonymous sources
      + Prominent coverage of high society and events
      + /Every single one of the above criteria is met by "new-media" outlets like Gawker and the Huffington Post/
    + You can take media criticism from a century ago, replace the names of newspapers with blogs and have the criticism be just as valid and applicable
    + Knowing how people manipulated the press in the yellow-journalism era tells you how to manipulate blogs today
  + The Modern (subscription) Press
    + Started with Adolph S. Ochs and the /New York Times/
    + Solicited subscriptions via telephone
    + Understood that if he could make subscriptions stick, he could provide quality journalism at the same prices as yellow press
    + Subscription model aligned incentives of newspaper more closely with readers
      + Readers who felt they'd been misled would unsubscribe, depriving paper of ongoing revenue stream
      + More stable revenue stream subsidized nuance
    + The /New York Times/ heralded the transition to reputation-driven journalism
    + Even today, when someone buys a newspaper at a newsstand, they're not buying based upon the headlines, they're usually buying based upon the "brand" of the paper
    + While the subscription model freed the newspaper from the tyranny of the masses, they now had to deal with a greater level of control from corporate leadership
+ The Death of Subscription, The Rebirth of Media Manipulation
  + With the rise of blogs, we're back to the one-off problem
  + Each article is like a mini-newspaper and must fight for attention on its own
  + Sites like Google News disaggregate content, removing reputational signals
  + We don't consume blogs by subscription
    + RSS is dead
      + /Not for me, it isn't!/
      + The top sources of traffic for news sites are social networks like Facebook and Twitter
  + The death of subscriptions means that blogs don't care about providing ongoing value
  + The stories that people hear about and read are the ones that "blow up" on social media
  + Popularity isn't the same as importance
  + RSS died because it allowed readers to be in control
    + /I'm not sure about that/
    + /I think RSS died because nobody ever made a good user interface for it/
    + /That plus the early incompatibilites between RSS and Atom feeds meant that it never made a good first impression, and so people even today have this impression of RSS as being something for technical people only/
  + Blogs are in vicious competition today, but it's competition on the terms of the publishers, not on the terms of the readers

* Chapter 9: Tactic 6: Make It All About The Headline
+ For media that has to deal with the one-off problem, it all comes down to the headline
+ Headline determines how many people click through to the story
+ The headlines of today are almost /exactly/ the same as the headlines from the yellow press of a century ago
+ The only difference is that today's headlines are shared on social media rather than shouted on street corners
+ Blog headlines have to compete with headlines from other blogs, whereas headlines from subscription media only compete with headlines from other stories within the same publication
+ Pick me! Pick me!
  + The headline for the Pentagon Papers story was "Vietnam Archive: A Consensus To Bomb Developed Before '64, Study Says"
  + Is such a pedestrian headline imaginable in today's media environment?
  + The New York Times was able to publish with a relatively staid headline that stated the facts but did not attempt to oversell them
  + Outside of subscription media, headlines have to compete to attract readers
  + In the era of stable mainstream press, there was a tradition of writing witty or funny headlines
  + That tradition has died because search engines and aggregators do not understand puns, and therefore stories with witty headlines rank lower than stories with headlines are stuffed with keywords
  + The only measure of a headline is whether it gets people to click on it - whether the headline matches the contents of the story or is aesthetically pleasing is a strictly secondary concern
  + When selling a story to a blog, make the headline obvious
  + The easier it is for a blogger to write a headline, the more likely they are to run your story

* Chapter 10: Tactic 7: Kill 'Em With Pageview Kindness
+ The breakthrough for blogging as an industry was the ability to track pageviews
+ Having hard pageview numbers allowed blogs to see which of their articles were doing well and which were flops
+ The disturbing science
  + In the era of Yellow Journalism, papers would use an editor's intuition to determine which headlines would drive circulation
  + In the blog era, that role is fulfilled by data scientists who use fine grained tracking data to determine exactly what drives "engagement"
  + Blogs don't care about material that's ordinary-looking but insightful and wonderful to read
+ Their metrics, your advantage
  + In practice, blogs measure 3 things
    + How many views did the story receive
    + How many comments did the story receive
    + Was the story picked up and linked to by more prominent blogs or mainstream media outlets
  + Getting coverage on a site may be as simple as sending a link to another blog that covered the story
    + Bloggers are herd animals
    + If another blog covered the story, it must be newsworthy
  + Another way to get blog coverage is to have a story that hits popular search engine keywords
  + Bloggers have to churn out roughly 12 stories a day - this does not leave time for thorough journalism
  + Once you have coverage the way to ensure future coverage is to ensure that your stories are a reliable source of pageviews
    + Signal-boost the story on social media
    + Use services like Outbrain and Taboola to get your clickbait headlines in front of more viewers
  + However, be careful what you wish for
    + Once bloggers see you as a reliable source of pageviews, they won't ever /stop/ covering you
    + When they run out of good news (or even real news) they'll start reporting on rumors
  + Metrics and pageview counts give blog editors the illusion of control and thus open them up to manipulation
+ Can't stand the silence
  + If you post something and nobody responds, what does it mean?
  + This is known as Warnock's Dilemma, after Brian Warnock, a USENET user who first described the phenomenon
  + Lack of response can mean many things:
    + The post is correct, well-written and needs no follow up or response
    + The post is complete and utter nonsense and isn't worth engaging with
    + No one read the post
    + No one understood the post or bothered to ask for clarification
    + No one cares about the post (i.e. people understood the post weren't interested enough in it to respond)
  + All of the above are unprofitable and/or risky, from the perspective of bloggers
    + The first and third alternatives are plainly unprofitable
    + The second alternative risks embarrasment
    + The fourth alternative means the post was too ambitious for its audience - people were too intimidated by the post to respond
    + The fifth alternative means the post was off-topic
  + As a result, blogs consider engagement and virality over usefulness, accuracy and insightful analysis
  + Leaving fake comments or sending fake emails about a post confirms that a post drives engagement, and biases the blogger to write more on that topic
  + In a sane world, we would see posts that get tens of thousands of comments as failures rather than wild successess
    + If a post gets that many comments, it's a sure sign that the comments section has gone off topic and has turned into a flamewar
    + However, in this world, a post like indicates extremely high levels of "engagement", which incentivizes bloggers to write more
+ Breaking the news
  + Blogs don't care if they get tricked, as long as they get their pagviews
  + Pageview journalism pulls towards one of two extremes - the provocative or the already known
  + Gives people all they /appear/ to want from the simplistic metrics used

* Chapter 11: Tactic 8: Use The Technology Against Itself
+ Everything that blogs write is constrained by the structure of the medium
+ This applies to all media, not just blogs
+ Example: television
  + TV is a visual medium
  + Can't show abstract ideas
  + When abstract ideas must be discussed on TV, you need a person to present them
  + This leads to the creation of "talking heads" and "pundits" whose job it is to personify and represent abstract ideas on TV
+ Hemmed in on all sides
  + Early bloggers had to show readers what was new on their site
  + Solution: reverse chronological order "stack"
  + New stories start at the top of the page and get pushed down
  + Stacking places emphasis on the present and the novel
  + In order to engage readers you constantly need something fresh at the top of the stack
  + "The best blogs update daily, if not hourly"
  + This need for fresh content at the top of the stack places tremendous pressure upon bloggers to find new stories
  + The best way to get traffic is to publish as frequently as possible
  + Don't bother investing effort into stories since they'll be at the top of the stack for only a short while
  + Huffington Post rule of thumb: readers will bounce off your story if it's more than 800 words long
  + Blogs have to keep their content visually appealing and geared towards "impulse" readers
    + A blog has about 1 sec to "hook" a reader
    + Bounce rates are incredibly high: >50% for many news sites
  + Eye-tracking studies
    + People start with the headline
    + They then scan down the left side of the page, looking for interesting sentences
    + If there's nothing interesting, they leave
    + The best way to keep readers is to have lots of short paragraphs, bulleted lists and subheadings
  + Jakob Nielsen
    + 40% of every article must be cut
    + But that's supposedly okay because cutting the article by 40% "only" reduces its value by 30%
  + Bloggers have to make reality fit the constraints of their platform, which leaves them open to manipulation
+ Making lemonade
  + Book promotion
    + Split a chapter into 8 separate posts
    + Get rid of all nuance through selective editing
  + Ryan is more than willing to work within the constraints of blogs as it allows him to introduce inaccuracies and distortions that favor his clients

* Chapter 12: Tactic 9: Just Make Stuff Up (Everyone Else Is Doing It)
+ Bloggers have to find the "angle" on every story they write
+ Don't have the luxury of spending time on a lead only to come up empty handed
+ Have to constantly scour social media and other sources for leads
+ Many local blogs scan Craigslist for leads, so creating "chatter" there can help get your story into blogs
+ Bloggers will publish anything if you can manufacture urgency around it
  + Give the same "exclusive" to multiple blogs and watch them race to publish first
  + Tell them you're going live with the story on your own website in the morning
+ Because bloggers have to find an angle, they always do
+ It's easy to make their job easier by leaving a deliberate trail for them to follow
+ Always wrong, never in doubt
  + If your site is famous and controversial enough, people will start writing false stories about it
  + One persistent blogger, writing article after article, will provide fodder for other bloggers, even though the articles may be totally false
  + Worse yet, this persistent kook will be rewarded with pageviews
  + Companies need to be on guard and ready to counterspin
  + The only form of defense is offense - replace controversy with less harmful controversy and let the new controversy push the old controversy down the stack
  + /In retrospect, this is exactly what the Trump campaign (intentionally or not) did - every week Trump had a new, different controversy, whereas Hillary just had one persistent controversy with her e-mails/
  + /As a result, most of Trump's controversies got "pushed down the stack" into oblivion, whereas the e-mail controversy with Hillary remained at the top of the stack long enough to gain significant traction/

** Chapter 13: Irin Carmon, The Daily Show and Me: The Perfect Storm of How Toxic Blogging Can Be
+ The first half of the book covered how blogs can be manipulated
+ Now we look at the consequences of that manipulation
+ How blogs create their own narratives for fun and profit
  + American Apparel contracted with a US manufacturer for some nail polish
  + Noticed that some bottles cracked or burst under bright halogen lighting
  + American Apparel decided to conduct a voluntary recall and told store managers to pull the bottles and store them in a cool, dry location until proper disposal instructions could be given
  + Jezebel blogger Irin Carmon picked up on this e-mail suggesting that American Apparel's nail polish contained hazardous material, even though the problem was with the glassware, not the nail polish
  + American Apparel was notified of the story minutes before it went live
    + Notification was a fig leaf designed to ensure that Irin Carmon could write, in all honesty, that American Apparel had been notified and had been given a chance to respond
  + The outcry against the nail polish led to the manufacturer falling behind on their other orders and eventually declaring bankruptcy
  + If it hadn't been for Irin Carmon, the matter could have been handled privately, and the company would still probably be operating today
  + Irin Carmon is just like Ryan Holiday - she is a media manipulator, even though she styles herself as a writer and a journalist
+ A Pattern of Manipulation
  + Daily Show sexism
    + Irin Carmon accused /The Daily Show/ of being sexist against women
    + There was no factual basis for this story - story was generated from a variety of anonymous and off-the-record sources
    + She did not seek comment from anyone currently working for the Daily Show
    + Story was widely circulated and republished - established Gawker Media's reputation as both a muckracker and an influencer
    + Even though women currently working for The Daily Show responded with a letter that said that Irin Carmon's accusations were baseless, the fact that their letter was a /response/ to the series of Carmon pieces meant that Carmon kept the initiative
    + When pressed by the New York Times to respond to the letter written by women currently working at The Daily Show, Carmon had no comment, even though she used the same lack of comment from The Daily Show as evidence that they had something to hide
    + Even though the original piece had been largely undermined by on-the-record responses from people currently working at The Daily Show, Irin Carmon continued to repeat unfounded accusations from earlier stories as established facts in later ones
    + Irin Carmon's goal was to establish a narrative that would drive pageviews for Jezebel - in this she was fantastically successful
    + The fact that this caused damage to others was not her concern
  + Judd Apatow
    + Irin Carmon goes up to Judd Apatow at a party and accuses him of being sexist
    + Apatow denies the accusation
    + Carmon prints the story as "Judd Apatow Defends His Record On Female Characters" -- implying that Apatow has something to defend
+ How one side learns from the other
  + In the last election, political groups of all stripes have picked up this playbook and used it to push their agendas
    + Pizzagate
    + Rumors about Hillary Clinton's health
    + E-mails
  + Tactic is known as "concern trolling" - feign outrage or concern in order to force your opponents to respond to accusations
  + By responding to the accusations, your opponents make the accusations seem real
  + If they don't respond, you can keep repeating the accusation until they have to respond
  + The fact that the Right has figured out the same playbook as the Left hasn't made things better; it's only made the truth harder to find

* Chapter 14: There Are Others: The Manipulator Hall of Fame
+ Shirley Sherrod controversy
  + Black woman who lost her job at the Department of Agriculture for allegedly making a racist speech
  + In reality the speech was about how /not/ to be racist
  + However, two short (less than 3 minutes each) clips from the 40 speech were posted out of context by Andrew Breitbart
  + They went viral and Ms. Sherrod lost her job
+ Even though Breitbart was proven wrong, the story still generated enough pageviews to be a winning stories
+ In fact, the eventual discrediting of the story was actually /favorable/ for Breitbart, because it allowed him to spin out the controversy for a longer period of time
+ Andrew Breitbart was one of the first masters of online media manipulation
  + Founded Breitbart.com
  + Founding employee of The Huffington Post
  + First employee of The Drudge Report
+ The master and his proteges
  + Even though Breitbart died of heart failure in 2012, his legacy lives in the form of three people who worked under him
    + Steve Bannon
      + Steve Bannon took over Breitbart.com and used his experience as Breitbart's lieutenant to manipulate the media's coverage of Donald Trump
      + Leveraged his position into a job as chief strategist to the President
    + James O'Keefe
      + Makes heavily "edited" documentaries which are used to discredit liberal groups
      + Most well known for shutting down ACORN with a heavily edited video that purported to show an ACORN advisor given a pimp advice about how to dodge taxes
      + In reality, O'Keefe did not wear the outlandish pimp's costume when he met with the advisor - that was edited in after the fact
      + While O'Keefe's works have all of the forms of serious investigative journalism, in reality they are hollow shells that rely upon heavy editing and editorializing to make their claims
    + Charles Johnson
      + Plants narratives in the media in order to create controversies
      + Runs a site called WeSearchr.com, which pays bounties for evidence for various allegations
+ Beating them at their own game
  + If people like Breitbart, Bannon, or O'Keefe make you angry, they have /won/
  + As we've seen above, anger just causes you to spread the controversy further
  + The way to beat them is to do the research and show everyone how these people are manipulating their sources
  + Taking their allegations at face value is a chump's game - there's no way for you to win
  + Example: How was Milo Yianopoulos discredited?
    + Milo was not discredited by college students rioting over his speeches
    + Those riots, in fact, made him stronger
    + He was discredited when a 16-year-old girl in Canada did a lot of background research and found comments that Milo had made defending pedophilia
    + The way you defeat alt-right trolls is not by getting angry and responding to what they're saying right now, it's by digging up the skeletons they inevitably have in their closets

* Chapter 15: Slactivism Is Not Activism: Resisting The Time and Mind Suck of Online Media
+ Most of the media you consume is optimized to distract you
  + Videos are optimized for length - long enough to distract you, short enough that you don't get bored
  + Autoplay keeps a constant stream of novel content in front of your eyes
+ Cheating is everywhere
  + "Thumbnail cheating"
    + Thumbnails for YouTube videos are drawn from frames at halfway, one-quarter, and three-quarters of the way through the video
    + Smart publishers put single frames there that misrepresent the content of the video in order to drive clicks
    + YouTube Partners get the ability to set thumbnails arbitrarily
+ Fake news
  + Satirical news sites increasingly mirror the form and structure of reputable news sites
  + People spread stories even though they know they're fake, because it makes them feel good
  + Real news misrepresents stories in order to appeal to people's pre-existing biases
  + Example: Ben Carson allegedly referred to slaves as "immigrants" in a speech to the Department of Housing and Urban Development
    + In reality Carson referred to slaves as "another group of immigrants" that were exploited even more, and who worked even harder
    + News sites deliberately twisted his words to imply that he'd referred to slaves as being no different than other immigrants to America
    + This was done by "reputable" news outlets like USA Today
  + It's okay to dislike someone or disagree with them, but if you're going to disagree with someone, make sure you're disagreeing over what they /actually/ said, not what someone told you they said
    + /This is especially true of e.g. James Damore/
      + /The whole Damore saga reads like an operationalized version of the theoretical principles in this book/
      + /Take a thirty page memo, strip out the nuance, strip out the references, strip out the supporting evidence, then leak it to a pageview-driven publication like Gizmodo, knowing that they'll excerpt the most inflammatory parts/
      + /Just because Fox News does it to us doesn't make it okay for us to do the same thing back/
+ Selling You To The Highest Bidder
  + Boxes with content "from our partners" is really just advertising
  + Anything that has "Taboola" or "Outbrain" on it is an ad
    + /Seriously? Do people not know that Taboola and Outbrain boxes are ad modules?/
  + These ads universally go to crappy content, because good content doesn't need to buy traffic
+ Drugged and Delusional: The Result
  + Narcotizing dysfunction
  + People consume busyness with action
  + They confuse reading about a topic with doing something about the topic
  + /"Wokeness" gets confused with action/
  + The kind of "engagement" that social media engenders is not the civic engagement that people have in mind when they hear the word
    + Facebook and Twitter optimize for engagement with Facebook and Twitter, not with the wider world
+ How To Make America Great Again
  + How can we talk about making anything great again when we don't even really know what the world is like
  + Online media is the "CNN effect" immensely magnified
  + /Media narratives today move on the order of minutes, which means that in order to be effective, you either have to be willing to be misunderstood, willing to engage in the same manipulation as your opponents, or do everything in secret/
    + /Politicians usually do the second, while government does the third - see the massive proliferation of classified information in the post 9-11 era/

* Chapter 16: Just Passing This Along: When No One Owns What They Say
+ It's a common theme on social media for people to share things that they don't know are true
+ You see this often on Twitter, with people saying retweet != endorsement
  + /This is bullshit, because why would you retweet something if you didn't endorse it?/
  + /Retweet without endorsement only has the purpose of spreading controversy and/or inaccurate information/
+ The delegation of trust
  + For a long time, all media followed basically the same rules, so it was all right for reporters to use each others work
  + Old rules
    1. If a publication is "legitimate", the stories inside it are legitimate
    2. If a story is legitimate, the facts inside it are legitimate
    3. If it can be assumed that the subject of a story is legitimate, then it can be assumed that what's being said about the subject is legitimate too
  + The old rules allowed journalists to build off each others' work instead of having to start from scratch
  + The web corrupted the delegation of trust with the "link economy"
    + In the old days, blogs lacked the resources to do original reporting
    + Blogs relied on other outlets to do original reporting, while they added analysis and commentary
      + /In a sense, early blogs were free riding on the work of legitimate news outlets/
    + However, the problem starts when blogs start linking to other blogs
    + The link economy encourages blogs to take from one another without verification, and creates an ever turning ratchet of outrage, as the most provocative blogs also get the most incoming links
  + Blogs persist in delegating trust and investing in the link economy even when the preconditions needed for those things to work -- reliable sources -- no longer exist
  + Example: Maurice Jarre
    + Maurice Jarre was a composer who died in 2001
    + When he died, an Irish student added a fabricated quote to his Wikipedia page: "When I die, there will be a final waltz that only I can hear."
    + This quote spread from Wikipedia into blogs
    + Eventually it was picked up by /The Guardian/, which was a "reputable" publication
    + At that point the quote was treated as real and the lie would have become fact if the student hadn't stepped forward
  + The link economy is designed to confirm and support, not to question or dig
  + Even though individual posts can be updated, there is no way to notify people who have been misinformed by the old version of the story
+ The link illusion
  + The more links an article has, the better supported it appears to be
  + In reality, those links could go anywhere, and the majority of readers aren't going to bother following them to find out
  + Only 44% of people searching for stories on Google News actually bother to click through to any of the stories
  + People read headlines and links and then assume that the story confirms whatever it is they want to believe
+ The breaking news excuse
  + Journalists often use the excuse of breaking news as a reason to not do due diligence
  + Many terms used to describe this practice
    + Iterative journalism
    + Process journalism
    + Beta journalism
  + In all cases, it calls for bloggers to publish /first/, then verify
  + Even though breaking news is used as the justification for this practice, breaking news is when you want to be /most/ careful, in order to avoid misleading people about a developing situation
  + Schopenhauer: journalists are like dogs: something moves and they start barking
  + Gawker: "publicly airing rumors is the best way to truth"
  + In fact, getting it wrong is often more profitable than getting it right -- every time a blog posts incorrect information, it can post a correction, thus gaining more pageviews
  + It can take only the slightest rumor or speculation for a blog to publish a story; blogs know that no one will remember the hundreds of times they published a rumor that turned out to be baseless if they manage to be prescient about a major event, such as a corporate takeover or major world event
  + In fact, if the false story makes enough of a splash, the blog can continue reporting on the reaction and the fallout from the story, leaving aside that the story is completely baseless
+ A broken philosophy
  + Compare online journalism to science
  + Science works because scientists attempt to replicate each others work, ensuring that a foundation is solid before they build on it
    + /Not anymore -- see "replication crisis"/
  + Bloggers forge ahead, treating rumors as reported truth
  + Blogging is self-referential, not self-critical
  + The epitome of this is the "neutral retweet" phenomenon, when people pass on rumors and speculation without endorsement
  + Everything you pass on should be endorsed -- what's the point of repeating something you think is false?
  + Old media had its flaws but they would at least attempt to verify a story before publishing it

* Chapter 17: Cyberwarfare: Battling It Out Online
+ In the old days, companies hired PR professionals to help spread the word about new initiatives or new products
+ Today, companies hire PR professionals to suppress false or misleading information
+ The implicit shakedown
  + Techcrunch threatens to release stories about companies without any warning if those companies don't release their news to Techcrunch first
  + Similar to the mob strategy of demanding "protection" money, or the Afghan practice of /ghabban/ -- demanding payment for protection from a threat that you create
+ A culture of fear
  + Social media experts have long since given up on blogs doing rigorous journalism
  + Instead, they advise their clients to be ready to do damage control
  + You never know when a blog is going to report a baseless negative story on you, and you never know which baseless negative stories are going to go viral, so you need to be ready to do damage control
  + Not a theoretical concern - baseless rumors that the iPhone would be delayed caused Apple's market valuation to drop by 4 billion dollars
  + This was evident during the Toyota "unintended acceleration" controversy
    + Allegations that some Toyota cars accelerated on their own
    + Later investigation (done by NASA) found that, although there were quality issues in Toyota's software, all actual cases of unintended acceleration could be attributed to driver error
    + However, investigations take time to complete, and in the meantime all sorts of baseless accusations can fly
    + A situation like the unintended acceleration fiasco can hurt a company twice over, since right when its critics are at their most vitriolic, the company may be unable to respond, because of advice from its legal team
+ Where there is smoke, there is fire
  + The trick is to repeat things until they sound true
  + This is especially easy to do on social media platforms, where automated "troll" or "astroturf" accounts can present the same reply while making it seem like they come from different people
+ Weaponizing Information
  + What we are beginning to see are the tools of online journalism being turned back against the journalists themselves
  + Uber has discussed hiring opposition researchers and bloggers to post incriminating evidence against journalists who questioned the company's hardball tactics
  + The media says that, in this day and age, suppressing journalism is the wrong approach
  + But that assumes that the information the media is reporting is accurate
  + That's not what's happening today -- the media today passes along whatever rumor, innuendo and hearsay it comes along, and leaves the judgments to the readers
  + The automatic treatment of accusation as fact is so easy to abuse, it's almost more difficult /not/ to abuse it
  + Example:
    + Ryan's friend was cheated by a media agency
    + No legal recourse -- the agency had a top-notch legal team
    + However, Ryan worked with this person's lawyer to draft a letter that signaled an /intent/ to file a lawsuit
    + This letter was then leaked to blogs like Gawker and TMZ before it was sent to the agency's lawyers
    + As a result, the friend got a $500,000 settlement from the agency
    + While in this case justice was served, at no point did anyone verify whether Ryan's friend's claims were baseless
+ You can only be unafraid if you're a nobody. And even then, who knows?
  + /Exactly -- ask James Damore, who was a "nobody" engineer at Google, until a memo that he wrote was leaked to Gizmodo/

* Chapter 18: The Myth of Corrections
+ Iterative journalism is only possible because people believe that stories can be corrected after the fact
+ The problem is that that belief is totally wrong
+ Example: Matt Drudge & Sidney Blumenthal:
  + Matt Drudge ran a story accusing Clinton adviser Sidney Blumenthal of abusing his wife
  + The story was totally fake and was given to Drudge by a Republican partisan who was out to get Blumenthal
  + Drudge admitted this in an interview with the Washington Post
  + Matt Drudge only retracted the story after Blumenthal sued, and even then, he expressed no remorse
+ Sensational lies always travel faster than the truth; this is why it's the reporter's job to correct for that and make sure that they've done their best to get the correct story
+ Correcting people who are wrong for a living
  + Ryan once gave /The Price Is Right/ a $500 American Apparel gift card to use as a prize
  + This was supposed to be an ironic bit of publicity -- brand that caters to millenials showing up on a show that's largely seen be people outside their core demographic
  + However, /Brand Channel/ assumed that the show was a commercial spoof of the actual Price Is Right
    + Didn't realize that Drew Carey was the new host
    + Wrote a piece implying that American Apparel was trying to "turn around" its image by filming a commerical featuring a spoof of Price Is Right
    + Piece was so wrong it was impossible to correct
  + Corrections are rarely effective because bloggers deliberately drag their feet on corrections
    + Stories do most of their traffic in the initial hours or days after they've been posted
    + A correction issued a week or month after the fact will be read by approximately no one
  + Corrections are often posted at the bottom of the article, because bloggers know that many people will skim the article and never get to the correction
+ Being wrong
  + Articles are composed of two things
    + Facts
    + Implications and assertions based upon those facts
  + A correction ought to trigger a reassessment of conclusions based upon the facts that were corrected, but it does not
+ The psychology of error
  + Even thought content is created iteratively, it is not consumed iteratively
  + People consume things like Wikipedia pages and blog posts as a final product
  + No one goes back to make sure that the fact they've cited is still valid
  + People are not normally good at suppressing their instinct to speculate until the totality of facts have arrived
  + Backfire effect
    + In some cases a correction can actually amplify the original incorrect belief
    + /The backfire effect, however, appears to have problems with reproducibility/
  + When exposed to fantastical wholly fictional headlines, readers did not increase their skepticism
  + Instead what happened was that their sense of what was real and what was not became skewed

* Chapter 19: The Twenty-First Century Degradation Ceremony
+ The hiddden purpose of blogs in today's society is to dispense public punishments
+ The degradation ceremony
  + Acts of ritualized destruction -> degradation ceremony
  + The purpose is to allow a group to ritually cast out one of its members
  + People enjoy taking part in degradation ceremonies, because it allows them to feel like they're increasing the purity of the group
  + Examples of targets of modern-day degradation targets:
    + Justine Sacco - tweeted an ill-advised joke about AIDS, and as a result lost her job and is now permanently tarred as a racist
    + Brian Williams - exaggerated a story and lost decades of goodwill
    + Monica Lewinsky - is now known only for her /consensual/ relationship with President Clinton
    + Jonah Lehrer - got caught recycling some of his own writings and got turned into a punching bag for journalists
  + The truth is that every one of us has something that could be taken out of context and spun into a story to make us look abhorrent
  + The problem with the Internet is that those opinions are easier than ever to find, and easier than ever to spin
  + Internet justice has no sense of proportionality - every "crime" deserves maximum punishment
  + Moreover, internet hate mobs tend to descend most on those who can least afford to defend themselves
+ Disagree with something? Just make fun of it
  + Snark: a statement that you disagree with, but which isn't substantive enough to respond to
    + Remark doesn't mean anything
    + Person doesn't care enough that you can meaningfully criticize them back
  + Snark is an effective weapon in enforcing norms and dismissing ideas
    + Don't like something? Just make fun of it until it goes away
    + /Though, depending on whether the people you're criticizing have their own supporters, snark may backfire/
    + /Hillary Clinton thought she was being snarky and cool when she told Donald Trump to, "Delete your account," but because Trump had a cadre of supporters willing to back him up, she just ended up looking weak/
    + When targeted my snark, your instinct will be to appeal to reason. /This is a mistake/
  + Bloggers love to use snark because it's cheap clickbait
    + Makes people chuckle, even though nothing of substance has been said
    + To be called a /douche/ or a /bro/ is to be characterized by all the attributes that society hates, but can't define
  + In the old days, if someone kept calling you names, and insulted you severely enough, you could challenge them to a duel
  + Dueling wasn't a great solution but it was /a solution/
  + But today, unless you have enormous wealth, you can't meaningfully respond to a blogger snarking about you
  + If we turn everyone into a laughingstock, the only type of person left will be people with nothing to lose: i.e. Donald Trump
    + /If I'm reading this correctly, Ryan is saying that, in a sense, Hillary Clinton's defeat was a result of the media system that ostensibly supported her/
    + /Bloggers need pageviews. In order to get pageviews, they have to serve cheap, but controversial content./
    + /Therefore, they use snark and insults. The problem is, Donald Trump is from reality TV. He can handle snark and insults. Hillary could not/
    + /Hypothesis: this would have brought down Bernie Sanders as well/
  + The only people who benefit from snark are those who have no reputation to begin with
    + Reality TV show stars
    + D-list celebrities
    + People who are known for being controversial, and nothing else
  + Trump wins because, in a sense, he's so shameless as to be immune to snark
  + So the next time you're about to make a snarky comment, think about the types of people who thrive in a snark-filled environment, and ask yourself whether you want more of those people
+ The cycle of building people up and tearing them down is accelerating
  + It used to be that you had to be an established national figure before you were subject to the sort of scrutiny that celebrities faced
  + However, today, that focus can be turned on anyone, regardless of how well equipped they are to deal with it
+ Bloggers, in particular, feel good when they're tearing people down
  + Journalism has been devastated by the rise of the Internet
  + Bloggers went to expensive grad school, and now they're forced to work in a boiler room environment churning out clickbait headlines
  + This fuels resentment, which makes it palatable to tear people down
  + "Rage of the creative underclass"
+ Unlike with Greek tragedy, there is no moral lesson to be learned from blogs - blogs encourage us to /gawk/, but not /learn/
  + /They don't even try to deny it - one of the most popular blogfarms was called Gawker/

* Chapter 20: Welcome To Unreality
+ The current media ecosystem has created a state of unreality
+ Fake and real can't be told apart easily
+ Fake stories have real consequences
+ A slow creep
  + The news, by definition, is what is unexpected
  + However, most things in life are expected
  + The news is not a summary of what has happened recently
  + It's not even a summary of the most important events
  + The news is a summary of the events that have been able to navigate the media's filters
  + The news funnel can be described as follows:
    + All that happens
    + All that's known by the media
    + All that's newsworthy
    + All that's published as news
    + All that spreads
  + You're only seeing the output of the bottom of that funnel
+ Embracing the fake
  + 2011 - Henry Blodget calls for marketers to stop pitching stories to Business Insider
  + Instead he told marketers to just go ahead and write stories for Business Insider and submit them
  + Blodget didn't care that he was passing on misinformation to his readers as long as it got pageviews for him
  + News sites allow this because they know that when someone is wrong, it generates far more traffic than if they were correct
  + News sites are driven by exactly the same incentives as reality TV -- it's just that we know that reality TV is manipulated, but we don't expect news to be manipulated in the same way
+ From the fake, the real
  + Simple process
    + Start with a fake event
    + Get publicity for it by trading it up the chain
    + Elicit real responses and action
  + Blur the lines between what is fake and what is real
  + Make the trivial seem important and the important seem trivial
  + The problem isn't that the news media is fake, the problem is that this fake reporting drives real action and events
  + In the run-up to the war on Iraq, Dick Cheney leaked false information something to the /New York Times/ and then cited his own leak on /Meet The Press/, to show that there was "real reporting" supporting the claim that Iraq had WMDs
  + By the time the real facts came out, it was too late -- the war had already begun

* Chapter 21: How To Read A Blog: An Update On Account of All The Lies
+ When a blog mentions a "tipster" or an anonymous source, they're probably being manipulated
+ When a blog mentions that it's "hearing reports", that might just mean they saw a tweet on the topic
+ When you see "leaked official documents", there's a good chance that the documents were leaked intentionally by the organization in order to get facts into the narrative via a back channel
+ Breaking news is news that's reached you too early
+ If you see the word "updated" on an article, know that no one bothered to rework the article's conclusions in light of the new information
+ When you see a story tagged "Exclusive", it means that the blog and the source of the story worked out a deal to ensure favorable coverage
+ When a blogger cites a source, they don't verify that the source actually says what they allege it says
+ When a blogger says that they've reached out to the target of a story for comment, but haven't heard back, it means that they sent an e-mail 2 minutes before the story went live
+ Relying on abandoned shells
  + We still believe that if someone takes the time to write something, there's something worth writing about
  + This was true in an era when writing was scarce, but now writing is plentiful
  + /In a sense, our information economy is now like our diet: the problem isn't that there isn't enough, the problem is that there's too much/
  + /Attention-seeking online media is the information equivalent of junk food/
+ The age of no authorities
  + Everyone is lying and conning
  + Citations and references used to be markers of authority, but now they've been cheapened to the point of being meaningless
  + However, we don't take them as meaningless
+ "If the news is important, it will find me"
  + This cliche worked in the old media ecosystem, but no longer
  + Now the fact that something makes it through your studied inattention doesn't mean that it's inherently important
  + It means that the news has been manipulated to be as attention-getting as possible
  + The news that finds you is the worst kind
    + News that angers
    + News that titillates
    + News that makes the world seem worse than it actually is

* Conclusion: So... Where To From Here?
+ It's a cliche now to hear journalists complaining about the news
+ Whereas television turned everything it touched into entertainment and comedy, Internet journalism turns everything it touches into outrage
+ Help and hope
  + When the first edition of the book was published in 2012, it seemed like no one was going to do anything
  + However, in the meantime Gawker has been destroyed by a lawsuit financed by Peter Thiel and filed by Hulk Hogan
  + Ironic that a news outlet that compared news to professional wrestling was destroyed by professional wrestler who refused to buy that excuse
  + People said that the Hulk Hogan verdict would have a chilling effect on online journalism
  + But maybe a chilling effect is what we need
  + Publishers need to learn that publishing false information has consequences
  + In 1890, Louis Brandeis published a piece arguing that new legal remedies were needed to deal with a media ecosystem that could damage reputations with false accusations faster than the truth could repair them
  + We need to draw a distinction between aggressive reporting and bullying
+ Other solutions
  + We need to challenge the fundamental economics of blogs
  + As it turns out, pageviews aren't actually all that valuable -- it can be more profitable to have a smaller site with a more dedicated audience than to have a large viewership
  + Paywalls are a good thing - realign incentives of publishers and readers
    + /The problem with a paywall, however, is that it encourages a different sort of distortion - ideological distortion/
    + /If pageview-driven journalism is a redux of the yellow press, reader-supported journalism is a redux of the party press -- the publication is incentivized to print that which its readers want to hear/
    + /That said, I still think that paywalls are better, overall, than pageview driven journalism; I would much rather have the publication have the time to do detailed reporting (even if that reporting has bias) than be forced to publish false information early in order to garner pageviews/
  + As readers, we need to hold blogs accountable when the publish false information
  + The current model only exists because readers have tacitly accepted the burden of cross-referencing and verifying information
  + When you read information, ask yourself, "What do I plan to do with this information?"
    + In many cases, the answer is nothing
    + In those cases, stop reading - the information is a waste of your time
  + Marketers need to learn that there is long-term reputation blow-back from the sort of outrage marketing that Ryan pioneered
    + American Apparel is no longer in business, partly because the outrage-driven marketing made the brand toxic over time
+ A new awareness
  + We need to readjust our expectations
  + News cannot be both /instant/ and /good/
    + /Again, just like food/
  + The purpose of this book was to expose the manipulations that media people do, so that those manipulations won't work any more
