#+TITLE: Review: A Crisis Is A Terrible Thing To Waste
#+OPTIONS: toc:nil; num:nil; ^:nil; ':t

* Summary
In /[[https://www.brookings.edu/wp-content/uploads/2019/01/fp_20190118_hass_a_crisis_is_a_terrible_thing_to_waste.pdf][A Crisis Is A Terrible Thing To Waste]]/, Ryan Haas argues that the the recent tensions between the US and China represent a structural shift in the US-China relationship. Instead of thinking of the current low ebb in relations as the result of the particular leadership style of Donald Trump, we must acknowledge that the US-China relationship no longer has the same logic that it had for the past 40 years, and we must forge a new set of principles for dealing with China if we are to avoid conflict.

The US-China relationship, as forged by Nixon and Premier Zhou Enlai with the Shanghai communique in 1972, envisioned China as a counterbalance to the Soviet Union, which was then the greatest strategic competitor to the United States. At the time, China, though Communist, was seen as being more amenable to US influence than the Soviet Union, and China's relative lack of economic and military development meant that it would not pose any kind of strategic threat to the United States for decades, if not longer.

This relationship was bolstered by Deng Xiaopoing's succession to the leadership of the Chinese Communist Party. Deng was seen as a reformer, who sought to make China more like a Western country in order to bolster China's economic, political and military strength, especially vis-à-vis the Soviet Union. While Deng's reputation as a reformer suffered greatly after the suppression of pro-democracy protests in Tianemen Square in 1989, overall opinion within the United States still held that China's long-term path was towards convergence with the West, and, in the meantime, it was still an important strategic counterbalance against the Soviet Union.

After the fall of the Soviet Union in the early '90s, the basis of the relationship between the US and China began to shift. The goal of the United States shifted from viewing China as a strategic counterbalance to the (no-longer existent) Soviet Union to viewing China as an emerging power who could and should be integrated into the global "rules-base international order". This culminated with China's accession to the World Trade Organization in 2001.

While there have been some notable successes resulting from attempts to integrate China into a rules-based international order, notably with cooperation on anti-piracy and sanctions against North Korea, today that strategy is regarded by many as having failed. Today, China is widely seen as being more of a strategic competitor rather than a potential partner. There is a growing political consensus in the US that Chinese economic growth has come at the expense of American workers, and that increasing engagement has not resulted in increasing liberalization, as many had predicted.

This change in view is due in part to an ebb in American power, as well as an increasingly assertive Chinese foreign policy. On the part of the US, defeats in Iraq and Afghanistan have shattered the post-Gulf War myth of American military invincibility, while the 2008 financial crisis and ongoing increases in economic inequality have led to growing doubts about the viability and stability of the American economic system.  

On the part of the Chinese, increasingly strident rhetoric about Taiwan and Hong Kong, fortification of island bases in the South China Sea, tensions with India over the Arunachal Pradesh region, and the creation of alternative financial and development instutions (like the Asian Infrastructure Development Bank, and the Belt-and-Road Initiative) have led many to conclude that China is no longer interested in integrating with Western international instutions, but rather that it wants to forge a parallel world order with itself at the center.

All of these shifts indicate that the trajectory of US-China relations, which had been on a path towards ever deeper integration, has shifted to a more adversarial one. The fact that few have acknowledged this shift means that there is an increasing risk of miscalculation by policy-makers on both sides. Leaders in Washington and Beijing need to re-examine their assumptions about the other side, and make new choices which acknowledge that the strategic imperative that brought the US and China together no longer exists.

As a result, the US must ask itself where it is willing to flex to accommodate a rising China, and where it must draw lines that it expects China to respect. It's clear that the US no longer has the ability to stymie China at will. It's equally clear that China is no longer willing (if it ever was) to take international rules as constant. As a result, the US and China need to find a new compromise which allows China a greater say in global governance without enabling it to carve out an exclusive sphere of influence in Asia. 

To do this, the US needs to fortify its partnerships with other powers in the region, without necessarily forcing an "us or them" choice in relations between the United States and China. Such a choice was viable when dealing with the Soviet Union, because the Warsaw Pact and Western Europe formed two very distinct economic entities, with only a trickle of trade between them. In contrast, China is the #1 or #2 trading partner for all US allies in Asia, often outranking the US itself. Forcing a choice between the US and China is just as likely to lead to US isolation and exclusion from Asia as it is to a strengthened anti-China alliance.

If the US acknowledges that the fundamental basis of US-China relations has changed, it's possible for the US to come to a new arrangement with China that accomodates Chinese growth, allows for healthy peaceful competition between the two powers and preserves the sovereignty of small countries in South Asia. The US needs to understand that reacting too aggressively to China can have as many dangers as reacting too passively, and that Chinese dominance of the future international system is not guaranteed. In the long run, a competitive but stable relationship with China is a better guarantee of long term security than outright hostility.

* Review
On the face of it, this paper seems to be quite reasonable. It lays out a succinct history of US-China relations, and identifies the ways in which the strategic basis behind that relationship has changed since Richard Nixon and Zhou Enlai "opened" China. It correctly states that the there has been a fundamental shift in the basis of this relationship, as the US has, at long last, acknowledged that Chinese "convergence" with Western international norms has largely been illusory.

My concern is that I think the paper understates the level of opposition that China has to what we would call the "rules-based international order". The paper envisions a future in which existing international instutitions have "flexed" to accomodate both China and the United States, and the two superpowers, while competing peacefully, are also cooperating on trans-national issues like piracy, terrorism, and climate change. I think this vision is a fantasy. 

Chinese leaders have repeatedly (and with reason) claimed that the current set of international institutions is a reflection of US power, and, as a result, these institutions are inherently biased towards the US and the preservation of American power. It's premature to conclude that the only reason China is building alternative institutions of its own is because it has been denied participation in existing institutions by the United States. It's equally plausible, to me, that China would have created alternative institutions of its own anyway, while using increased participation in Western institutions to sabotage them from within. 

I also think that the paper overstates the convergence of values between China and the US with regards to transnational threats. While China has been willing to cooperate with the West on fighting piracy off the Horn of Africa, the Chinese leadership doesn't seem to be willing to embrace the "global police" role that the US and EU embrace with regards to Africa. Even though China has extensive infrastructure project in Africa, it has not shown any proclivity to intervene against militant groups or bolster the governing institutions of the African states it deals with. Instead, its focus appears to be narrowly focused on guranteeing security for its own workers and infrastructure without regard for broader regional stability.

Finally, my biggest objection to the paper is that it assumes a level of coherent policy-making on the part of the United States that does not exist and has not existed for almost 15 years. The paper repeatedly asks US "policymakers" to ask themselves questions and come to a consensus on China. Why would we expect them to do such a thing when they have been unable to come to a consensus on almost anything else? I'm sick of papers that come out of Brookings (and other think tanks) that assume that the US still has the ability to effectively craft long-term policy, when in reality the US can't even agree on a budget for the next year. Where is the policy paper that sets out what the US ought to do in the next six months to one year to avoid conflict with China?
