#+TITLE: Why I didn't like The Last Jedi

As someone who personally did not like The Last Jedi, I would suggest that ordinary people value movies on plot. TLJ's plot was very loose, bordering on incoherent. Even as someone intimately familiar with the Star Wars universe and backstory, I had trouble following it at times. For someone less familiar than I, the movie would have made no sense, from a plot perspective.

However, for a film critic, that would have been balanced out by the fact that the cinematography and special effects were quite good. The big vistas, over alien worlds, particularly, were quite well done. But while that sort of thing is important to a film critic, it's not nearly as important to the average moviegoer who wants to sit down and watch an easy-to-understand story in roughly 90-120 minutes.

And that brings me to my final critique of TLJ. The movie was **long**, and worse, it **felt long**. There simply wasn't enough content for two hours and thirty-five minutes of screen time, and as a result, it felt like scenes were stretched out unnecessarily. Star Wars movies are not supposed to be boring, yet in this one I felt completely bored on multiple occasions. So I would suggest that the wildly varying differences in ratings between critics and ordinary viewers comes down to people valuing movies on different metrics. As a vehicle for telling a story, TLJ doesn't work so well. But as visual art? It's quite good.

Fans of TLJ compare it to The Empire Strikes Back, but Empire's plot is **tight**. Every scene, every action, is a stepping stone towards Luke's climactic showdown with Darth Vader in Cloud City. There's a constant feeling of suspense, as you watch Han and Leia flee from Imperial forces through a variety of settings (Hoth, asteroid belts, etc) while dealing with mechanical failures and spaceship-sized carnivorous worms. Meanwhile, on Dagobah, Luke is intensely training with Master Yoda, struggling to gain mastery over his abilities with the Force, and wrestling with the choice of whether to continue training or attempt a rescue with his current (inadequate) skills and strength. All of these threads come together in Cloud City, where we see that even after intense training, Luke is still little more than a novice compared to Vader, and that despite all of their resourcefulness and determination, the Rebel Alliance has to flee before the crushing logistical superiority of the Empire.

TLJ has many of the same themes, but executes them much more poorly. The entire sequence where Finn and Rose sneak off the Rebel flagship, go to the casino planet, and then attempt to disable the tracker on the Imperial flagship contributes almost nothing to the overall plot, and just serves to confuse the storyline. Rey's training with Luke has none of the anticipation that Luke's training with Yoda had. The "chase", rather than being an action packed sequence of scenes going through a variety of settings with various characters (bounty hunters, Lando Calrissian, etc) consisted of literally two starships following each other through empty space... for two hours.

A lot of my frustration with TLJ comes from the fact that it **could** have been as good as Empire Strikes Back... but it isn't because it was incompetently executed.
